/**
 * Geo Spatial Query Api - US Census Boundaries and Census Data
 * Easily integrate geospatial point-in-polygon search, census boundaries, location-based data, geofencing, and other location-based features into web and mobile apps. Our Software Development Kit (SDK) is available on GitHub at https://github.com/geospatialqueryapi/geospatialqueryapi-sdk. If possible then we are strongly recommending using our tested libraries available on GitHub, rather than creating new ones. PDF documentation - ./pdf.html
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mobiledatabooks@mobiledatabooks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Acs5ProfilesValuesDP0409DP040080E from './Acs5ProfilesValuesDP0409DP040080E';
import Acs5ProfilesValuesDP0409DP040081E from './Acs5ProfilesValuesDP0409DP040081E';
import Acs5ProfilesValuesDP0409DP040081PE from './Acs5ProfilesValuesDP0409DP040081PE';
import Acs5ProfilesValuesDP0409DP040082E from './Acs5ProfilesValuesDP0409DP040082E';
import Acs5ProfilesValuesDP0409DP040082PE from './Acs5ProfilesValuesDP0409DP040082PE';
import Acs5ProfilesValuesDP0409DP040083E from './Acs5ProfilesValuesDP0409DP040083E';
import Acs5ProfilesValuesDP0409DP040083PE from './Acs5ProfilesValuesDP0409DP040083PE';
import Acs5ProfilesValuesDP0409DP040084E from './Acs5ProfilesValuesDP0409DP040084E';
import Acs5ProfilesValuesDP0409DP040084PE from './Acs5ProfilesValuesDP0409DP040084PE';
import Acs5ProfilesValuesDP0409DP040085E from './Acs5ProfilesValuesDP0409DP040085E';
import Acs5ProfilesValuesDP0409DP040085PE from './Acs5ProfilesValuesDP0409DP040085PE';
import Acs5ProfilesValuesDP0409DP040086E from './Acs5ProfilesValuesDP0409DP040086E';
import Acs5ProfilesValuesDP0409DP040086PE from './Acs5ProfilesValuesDP0409DP040086PE';
import Acs5ProfilesValuesDP0409DP040087E from './Acs5ProfilesValuesDP0409DP040087E';
import Acs5ProfilesValuesDP0409DP040087PE from './Acs5ProfilesValuesDP0409DP040087PE';
import Acs5ProfilesValuesDP0409DP040088E from './Acs5ProfilesValuesDP0409DP040088E';
import Acs5ProfilesValuesDP0409DP040088PE from './Acs5ProfilesValuesDP0409DP040088PE';
import Acs5ProfilesValuesDP0409DP040089E from './Acs5ProfilesValuesDP0409DP040089E';
import Acs5ProfilesValuesDP0409DP040109E from './Acs5ProfilesValuesDP0409DP040109E';

/**
 * The Acs5ProfilesValuesDP0409 model module.
 * @module model/Acs5ProfilesValuesDP0409
 * @version 1.0.0
 */
class Acs5ProfilesValuesDP0409 {
    /**
     * Constructs a new <code>Acs5ProfilesValuesDP0409</code>.
     * @alias module:model/Acs5ProfilesValuesDP0409
     * @param mDBGroupName {String} 
     * @param mDBGroupCode {String} 
     * @param dP040080E {module:model/Acs5ProfilesValuesDP0409DP040080E} 
     * @param dP040081E {module:model/Acs5ProfilesValuesDP0409DP040081E} 
     * @param dP040081PE {module:model/Acs5ProfilesValuesDP0409DP040081PE} 
     * @param dP040082E {module:model/Acs5ProfilesValuesDP0409DP040082E} 
     * @param dP040082PE {module:model/Acs5ProfilesValuesDP0409DP040082PE} 
     * @param dP040083E {module:model/Acs5ProfilesValuesDP0409DP040083E} 
     * @param dP040083PE {module:model/Acs5ProfilesValuesDP0409DP040083PE} 
     * @param dP040084E {module:model/Acs5ProfilesValuesDP0409DP040084E} 
     * @param dP040084PE {module:model/Acs5ProfilesValuesDP0409DP040084PE} 
     * @param dP040085E {module:model/Acs5ProfilesValuesDP0409DP040085E} 
     * @param dP040085PE {module:model/Acs5ProfilesValuesDP0409DP040085PE} 
     * @param dP040086E {module:model/Acs5ProfilesValuesDP0409DP040086E} 
     * @param dP040086PE {module:model/Acs5ProfilesValuesDP0409DP040086PE} 
     * @param dP040087E {module:model/Acs5ProfilesValuesDP0409DP040087E} 
     * @param dP040087PE {module:model/Acs5ProfilesValuesDP0409DP040087PE} 
     * @param dP040088E {module:model/Acs5ProfilesValuesDP0409DP040088E} 
     * @param dP040088PE {module:model/Acs5ProfilesValuesDP0409DP040088PE} 
     * @param dP040089E {module:model/Acs5ProfilesValuesDP0409DP040089E} 
     * @param dP040109E {module:model/Acs5ProfilesValuesDP0409DP040109E} 
     */
    constructor(mDBGroupName, mDBGroupCode, dP040080E, dP040081E, dP040081PE, dP040082E, dP040082PE, dP040083E, dP040083PE, dP040084E, dP040084PE, dP040085E, dP040085PE, dP040086E, dP040086PE, dP040087E, dP040087PE, dP040088E, dP040088PE, dP040089E, dP040109E) { 
        
        Acs5ProfilesValuesDP0409.initialize(this, mDBGroupName, mDBGroupCode, dP040080E, dP040081E, dP040081PE, dP040082E, dP040082PE, dP040083E, dP040083PE, dP040084E, dP040084PE, dP040085E, dP040085PE, dP040086E, dP040086PE, dP040087E, dP040087PE, dP040088E, dP040088PE, dP040089E, dP040109E);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, mDBGroupName, mDBGroupCode, dP040080E, dP040081E, dP040081PE, dP040082E, dP040082PE, dP040083E, dP040083PE, dP040084E, dP040084PE, dP040085E, dP040085PE, dP040086E, dP040086PE, dP040087E, dP040087PE, dP040088E, dP040088PE, dP040089E, dP040109E) { 
        obj['MDBGroupName'] = mDBGroupName;
        obj['MDBGroupCode'] = mDBGroupCode;
        obj['DP040080E'] = dP040080E;
        obj['DP040081E'] = dP040081E;
        obj['DP040081PE'] = dP040081PE;
        obj['DP040082E'] = dP040082E;
        obj['DP040082PE'] = dP040082PE;
        obj['DP040083E'] = dP040083E;
        obj['DP040083PE'] = dP040083PE;
        obj['DP040084E'] = dP040084E;
        obj['DP040084PE'] = dP040084PE;
        obj['DP040085E'] = dP040085E;
        obj['DP040085PE'] = dP040085PE;
        obj['DP040086E'] = dP040086E;
        obj['DP040086PE'] = dP040086PE;
        obj['DP040087E'] = dP040087E;
        obj['DP040087PE'] = dP040087PE;
        obj['DP040088E'] = dP040088E;
        obj['DP040088PE'] = dP040088PE;
        obj['DP040089E'] = dP040089E;
        obj['DP040109E'] = dP040109E;
    }

    /**
     * Constructs a <code>Acs5ProfilesValuesDP0409</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Acs5ProfilesValuesDP0409} obj Optional instance to populate.
     * @return {module:model/Acs5ProfilesValuesDP0409} The populated <code>Acs5ProfilesValuesDP0409</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Acs5ProfilesValuesDP0409();

            if (data.hasOwnProperty('MDBGroupName')) {
                obj['MDBGroupName'] = ApiClient.convertToType(data['MDBGroupName'], 'String');
            }
            if (data.hasOwnProperty('MDBGroupCode')) {
                obj['MDBGroupCode'] = ApiClient.convertToType(data['MDBGroupCode'], 'String');
            }
            if (data.hasOwnProperty('DP040080E')) {
                obj['DP040080E'] = Acs5ProfilesValuesDP0409DP040080E.constructFromObject(data['DP040080E']);
            }
            if (data.hasOwnProperty('DP040081E')) {
                obj['DP040081E'] = Acs5ProfilesValuesDP0409DP040081E.constructFromObject(data['DP040081E']);
            }
            if (data.hasOwnProperty('DP040081PE')) {
                obj['DP040081PE'] = Acs5ProfilesValuesDP0409DP040081PE.constructFromObject(data['DP040081PE']);
            }
            if (data.hasOwnProperty('DP040082E')) {
                obj['DP040082E'] = Acs5ProfilesValuesDP0409DP040082E.constructFromObject(data['DP040082E']);
            }
            if (data.hasOwnProperty('DP040082PE')) {
                obj['DP040082PE'] = Acs5ProfilesValuesDP0409DP040082PE.constructFromObject(data['DP040082PE']);
            }
            if (data.hasOwnProperty('DP040083E')) {
                obj['DP040083E'] = Acs5ProfilesValuesDP0409DP040083E.constructFromObject(data['DP040083E']);
            }
            if (data.hasOwnProperty('DP040083PE')) {
                obj['DP040083PE'] = Acs5ProfilesValuesDP0409DP040083PE.constructFromObject(data['DP040083PE']);
            }
            if (data.hasOwnProperty('DP040084E')) {
                obj['DP040084E'] = Acs5ProfilesValuesDP0409DP040084E.constructFromObject(data['DP040084E']);
            }
            if (data.hasOwnProperty('DP040084PE')) {
                obj['DP040084PE'] = Acs5ProfilesValuesDP0409DP040084PE.constructFromObject(data['DP040084PE']);
            }
            if (data.hasOwnProperty('DP040085E')) {
                obj['DP040085E'] = Acs5ProfilesValuesDP0409DP040085E.constructFromObject(data['DP040085E']);
            }
            if (data.hasOwnProperty('DP040085PE')) {
                obj['DP040085PE'] = Acs5ProfilesValuesDP0409DP040085PE.constructFromObject(data['DP040085PE']);
            }
            if (data.hasOwnProperty('DP040086E')) {
                obj['DP040086E'] = Acs5ProfilesValuesDP0409DP040086E.constructFromObject(data['DP040086E']);
            }
            if (data.hasOwnProperty('DP040086PE')) {
                obj['DP040086PE'] = Acs5ProfilesValuesDP0409DP040086PE.constructFromObject(data['DP040086PE']);
            }
            if (data.hasOwnProperty('DP040087E')) {
                obj['DP040087E'] = Acs5ProfilesValuesDP0409DP040087E.constructFromObject(data['DP040087E']);
            }
            if (data.hasOwnProperty('DP040087PE')) {
                obj['DP040087PE'] = Acs5ProfilesValuesDP0409DP040087PE.constructFromObject(data['DP040087PE']);
            }
            if (data.hasOwnProperty('DP040088E')) {
                obj['DP040088E'] = Acs5ProfilesValuesDP0409DP040088E.constructFromObject(data['DP040088E']);
            }
            if (data.hasOwnProperty('DP040088PE')) {
                obj['DP040088PE'] = Acs5ProfilesValuesDP0409DP040088PE.constructFromObject(data['DP040088PE']);
            }
            if (data.hasOwnProperty('DP040089E')) {
                obj['DP040089E'] = Acs5ProfilesValuesDP0409DP040089E.constructFromObject(data['DP040089E']);
            }
            if (data.hasOwnProperty('DP040109E')) {
                obj['DP040109E'] = Acs5ProfilesValuesDP0409DP040109E.constructFromObject(data['DP040109E']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} MDBGroupName
 */
Acs5ProfilesValuesDP0409.prototype['MDBGroupName'] = undefined;

/**
 * @member {String} MDBGroupCode
 */
Acs5ProfilesValuesDP0409.prototype['MDBGroupCode'] = undefined;

/**
 * @member {module:model/Acs5ProfilesValuesDP0409DP040080E} DP040080E
 */
Acs5ProfilesValuesDP0409.prototype['DP040080E'] = undefined;

/**
 * @member {module:model/Acs5ProfilesValuesDP0409DP040081E} DP040081E
 */
Acs5ProfilesValuesDP0409.prototype['DP040081E'] = undefined;

/**
 * @member {module:model/Acs5ProfilesValuesDP0409DP040081PE} DP040081PE
 */
Acs5ProfilesValuesDP0409.prototype['DP040081PE'] = undefined;

/**
 * @member {module:model/Acs5ProfilesValuesDP0409DP040082E} DP040082E
 */
Acs5ProfilesValuesDP0409.prototype['DP040082E'] = undefined;

/**
 * @member {module:model/Acs5ProfilesValuesDP0409DP040082PE} DP040082PE
 */
Acs5ProfilesValuesDP0409.prototype['DP040082PE'] = undefined;

/**
 * @member {module:model/Acs5ProfilesValuesDP0409DP040083E} DP040083E
 */
Acs5ProfilesValuesDP0409.prototype['DP040083E'] = undefined;

/**
 * @member {module:model/Acs5ProfilesValuesDP0409DP040083PE} DP040083PE
 */
Acs5ProfilesValuesDP0409.prototype['DP040083PE'] = undefined;

/**
 * @member {module:model/Acs5ProfilesValuesDP0409DP040084E} DP040084E
 */
Acs5ProfilesValuesDP0409.prototype['DP040084E'] = undefined;

/**
 * @member {module:model/Acs5ProfilesValuesDP0409DP040084PE} DP040084PE
 */
Acs5ProfilesValuesDP0409.prototype['DP040084PE'] = undefined;

/**
 * @member {module:model/Acs5ProfilesValuesDP0409DP040085E} DP040085E
 */
Acs5ProfilesValuesDP0409.prototype['DP040085E'] = undefined;

/**
 * @member {module:model/Acs5ProfilesValuesDP0409DP040085PE} DP040085PE
 */
Acs5ProfilesValuesDP0409.prototype['DP040085PE'] = undefined;

/**
 * @member {module:model/Acs5ProfilesValuesDP0409DP040086E} DP040086E
 */
Acs5ProfilesValuesDP0409.prototype['DP040086E'] = undefined;

/**
 * @member {module:model/Acs5ProfilesValuesDP0409DP040086PE} DP040086PE
 */
Acs5ProfilesValuesDP0409.prototype['DP040086PE'] = undefined;

/**
 * @member {module:model/Acs5ProfilesValuesDP0409DP040087E} DP040087E
 */
Acs5ProfilesValuesDP0409.prototype['DP040087E'] = undefined;

/**
 * @member {module:model/Acs5ProfilesValuesDP0409DP040087PE} DP040087PE
 */
Acs5ProfilesValuesDP0409.prototype['DP040087PE'] = undefined;

/**
 * @member {module:model/Acs5ProfilesValuesDP0409DP040088E} DP040088E
 */
Acs5ProfilesValuesDP0409.prototype['DP040088E'] = undefined;

/**
 * @member {module:model/Acs5ProfilesValuesDP0409DP040088PE} DP040088PE
 */
Acs5ProfilesValuesDP0409.prototype['DP040088PE'] = undefined;

/**
 * @member {module:model/Acs5ProfilesValuesDP0409DP040089E} DP040089E
 */
Acs5ProfilesValuesDP0409.prototype['DP040089E'] = undefined;

/**
 * @member {module:model/Acs5ProfilesValuesDP0409DP040109E} DP040109E
 */
Acs5ProfilesValuesDP0409.prototype['DP040109E'] = undefined;






export default Acs5ProfilesValuesDP0409;

