/**
 * Geo Spatial Query Api - US Census Boundaries and Census Data
 * Easily integrate geospatial point-in-polygon search, census boundaries, location-based data, geofencing, and other location-based features into web and mobile apps. Our Software Development Kit (SDK) is available on GitHub at https://github.com/geospatialqueryapi/geospatialqueryapi-sdk. If possible then we are strongly recommending using our tested libraries available on GitHub, rather than creating new ones.      Copyright © 2021 Mobile Data Books, LLC. All Rights Reserved.  
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mobiledatabooks@mobiledatabooks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Acs5ProfilesValuesDP0401DP040001E from './Acs5ProfilesValuesDP0401DP040001E';
import Acs5ProfilesValuesDP0401DP040002E from './Acs5ProfilesValuesDP0401DP040002E';
import Acs5ProfilesValuesDP0401DP040002PE from './Acs5ProfilesValuesDP0401DP040002PE';
import Acs5ProfilesValuesDP0401DP040003E from './Acs5ProfilesValuesDP0401DP040003E';
import Acs5ProfilesValuesDP0401DP040003PE from './Acs5ProfilesValuesDP0401DP040003PE';
import Acs5ProfilesValuesDP0401DP040004E from './Acs5ProfilesValuesDP0401DP040004E';
import Acs5ProfilesValuesDP0401DP040005E from './Acs5ProfilesValuesDP0401DP040005E';

/**
 * The Acs5ProfilesValuesDP0401 model module.
 * @module model/Acs5ProfilesValuesDP0401
 * @version 1.0.0
 */
class Acs5ProfilesValuesDP0401 {
    /**
     * Constructs a new <code>Acs5ProfilesValuesDP0401</code>.
     * @alias module:model/Acs5ProfilesValuesDP0401
     * @param mDBGroupName {String} 
     * @param mDBGroupCode {String} 
     * @param dP040001E {module:model/Acs5ProfilesValuesDP0401DP040001E} 
     * @param dP040002E {module:model/Acs5ProfilesValuesDP0401DP040002E} 
     * @param dP040002PE {module:model/Acs5ProfilesValuesDP0401DP040002PE} 
     * @param dP040003E {module:model/Acs5ProfilesValuesDP0401DP040003E} 
     * @param dP040003PE {module:model/Acs5ProfilesValuesDP0401DP040003PE} 
     * @param dP040004E {module:model/Acs5ProfilesValuesDP0401DP040004E} 
     * @param dP040005E {module:model/Acs5ProfilesValuesDP0401DP040005E} 
     */
    constructor(mDBGroupName, mDBGroupCode, dP040001E, dP040002E, dP040002PE, dP040003E, dP040003PE, dP040004E, dP040005E) { 
        
        Acs5ProfilesValuesDP0401.initialize(this, mDBGroupName, mDBGroupCode, dP040001E, dP040002E, dP040002PE, dP040003E, dP040003PE, dP040004E, dP040005E);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, mDBGroupName, mDBGroupCode, dP040001E, dP040002E, dP040002PE, dP040003E, dP040003PE, dP040004E, dP040005E) { 
        obj['MDBGroupName'] = mDBGroupName;
        obj['MDBGroupCode'] = mDBGroupCode;
        obj['DP040001E'] = dP040001E;
        obj['DP040002E'] = dP040002E;
        obj['DP040002PE'] = dP040002PE;
        obj['DP040003E'] = dP040003E;
        obj['DP040003PE'] = dP040003PE;
        obj['DP040004E'] = dP040004E;
        obj['DP040005E'] = dP040005E;
    }

    /**
     * Constructs a <code>Acs5ProfilesValuesDP0401</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Acs5ProfilesValuesDP0401} obj Optional instance to populate.
     * @return {module:model/Acs5ProfilesValuesDP0401} The populated <code>Acs5ProfilesValuesDP0401</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Acs5ProfilesValuesDP0401();

            if (data.hasOwnProperty('MDBGroupName')) {
                obj['MDBGroupName'] = ApiClient.convertToType(data['MDBGroupName'], 'String');
            }
            if (data.hasOwnProperty('MDBGroupCode')) {
                obj['MDBGroupCode'] = ApiClient.convertToType(data['MDBGroupCode'], 'String');
            }
            if (data.hasOwnProperty('DP040001E')) {
                obj['DP040001E'] = Acs5ProfilesValuesDP0401DP040001E.constructFromObject(data['DP040001E']);
            }
            if (data.hasOwnProperty('DP040002E')) {
                obj['DP040002E'] = Acs5ProfilesValuesDP0401DP040002E.constructFromObject(data['DP040002E']);
            }
            if (data.hasOwnProperty('DP040002PE')) {
                obj['DP040002PE'] = Acs5ProfilesValuesDP0401DP040002PE.constructFromObject(data['DP040002PE']);
            }
            if (data.hasOwnProperty('DP040003E')) {
                obj['DP040003E'] = Acs5ProfilesValuesDP0401DP040003E.constructFromObject(data['DP040003E']);
            }
            if (data.hasOwnProperty('DP040003PE')) {
                obj['DP040003PE'] = Acs5ProfilesValuesDP0401DP040003PE.constructFromObject(data['DP040003PE']);
            }
            if (data.hasOwnProperty('DP040004E')) {
                obj['DP040004E'] = Acs5ProfilesValuesDP0401DP040004E.constructFromObject(data['DP040004E']);
            }
            if (data.hasOwnProperty('DP040005E')) {
                obj['DP040005E'] = Acs5ProfilesValuesDP0401DP040005E.constructFromObject(data['DP040005E']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} MDBGroupName
 */
Acs5ProfilesValuesDP0401.prototype['MDBGroupName'] = undefined;

/**
 * @member {String} MDBGroupCode
 */
Acs5ProfilesValuesDP0401.prototype['MDBGroupCode'] = undefined;

/**
 * @member {module:model/Acs5ProfilesValuesDP0401DP040001E} DP040001E
 */
Acs5ProfilesValuesDP0401.prototype['DP040001E'] = undefined;

/**
 * @member {module:model/Acs5ProfilesValuesDP0401DP040002E} DP040002E
 */
Acs5ProfilesValuesDP0401.prototype['DP040002E'] = undefined;

/**
 * @member {module:model/Acs5ProfilesValuesDP0401DP040002PE} DP040002PE
 */
Acs5ProfilesValuesDP0401.prototype['DP040002PE'] = undefined;

/**
 * @member {module:model/Acs5ProfilesValuesDP0401DP040003E} DP040003E
 */
Acs5ProfilesValuesDP0401.prototype['DP040003E'] = undefined;

/**
 * @member {module:model/Acs5ProfilesValuesDP0401DP040003PE} DP040003PE
 */
Acs5ProfilesValuesDP0401.prototype['DP040003PE'] = undefined;

/**
 * @member {module:model/Acs5ProfilesValuesDP0401DP040004E} DP040004E
 */
Acs5ProfilesValuesDP0401.prototype['DP040004E'] = undefined;

/**
 * @member {module:model/Acs5ProfilesValuesDP0401DP040005E} DP040005E
 */
Acs5ProfilesValuesDP0401.prototype['DP040005E'] = undefined;






export default Acs5ProfilesValuesDP0401;

