/**
 * Geo Spatial Query Api - US Census Boundaries and Census Data
 * Easily integrate geospatial point-in-polygon search, census boundaries, location-based data, geofencing, and other location-based features into web and mobile apps. Our Software Development Kit (SDK) is available on GitHub at https://github.com/geospatialqueryapi/geospatialqueryapi-sdk. If possible then we are strongly recommending using our tested libraries available on GitHub, rather than creating new ones. PDF documentation - ./pdf.html
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mobiledatabooks@mobiledatabooks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Acs5ProfilesValuesDP0301DP030001E from './Acs5ProfilesValuesDP0301DP030001E';
import Acs5ProfilesValuesDP0301DP030002E from './Acs5ProfilesValuesDP0301DP030002E';
import Acs5ProfilesValuesDP0301DP030002PE from './Acs5ProfilesValuesDP0301DP030002PE';
import Acs5ProfilesValuesDP0301DP030004E from './Acs5ProfilesValuesDP0301DP030004E';
import Acs5ProfilesValuesDP0301DP030004PE from './Acs5ProfilesValuesDP0301DP030004PE';
import Acs5ProfilesValuesDP0301DP030005E from './Acs5ProfilesValuesDP0301DP030005E';
import Acs5ProfilesValuesDP0301DP030005PE from './Acs5ProfilesValuesDP0301DP030005PE';
import Acs5ProfilesValuesDP0301DP030006E from './Acs5ProfilesValuesDP0301DP030006E';
import Acs5ProfilesValuesDP0301DP030006PE from './Acs5ProfilesValuesDP0301DP030006PE';
import Acs5ProfilesValuesDP0301DP030007E from './Acs5ProfilesValuesDP0301DP030007E';
import Acs5ProfilesValuesDP0301DP030007PE from './Acs5ProfilesValuesDP0301DP030007PE';
import Acs5ProfilesValuesDP0301DP030008E from './Acs5ProfilesValuesDP0301DP030008E';
import Acs5ProfilesValuesDP0301DP030008PE from './Acs5ProfilesValuesDP0301DP030008PE';
import Acs5ProfilesValuesDP0301DP030009PE from './Acs5ProfilesValuesDP0301DP030009PE';
import Acs5ProfilesValuesDP0301DP030010E from './Acs5ProfilesValuesDP0301DP030010E';
import Acs5ProfilesValuesDP0301DP030010PE from './Acs5ProfilesValuesDP0301DP030010PE';
import Acs5ProfilesValuesDP0301DP030014E from './Acs5ProfilesValuesDP0301DP030014E';
import Acs5ProfilesValuesDP0301DP030014PE from './Acs5ProfilesValuesDP0301DP030014PE';
import Acs5ProfilesValuesDP0301DP030016E from './Acs5ProfilesValuesDP0301DP030016E';
import Acs5ProfilesValuesDP0301DP030016PE from './Acs5ProfilesValuesDP0301DP030016PE';

/**
 * The Acs5ProfilesValuesDP0301 model module.
 * @module model/Acs5ProfilesValuesDP0301
 * @version 1.0.0
 */
class Acs5ProfilesValuesDP0301 {
    /**
     * Constructs a new <code>Acs5ProfilesValuesDP0301</code>.
     * EMPLOYMENT STATUS
     * @alias module:model/Acs5ProfilesValuesDP0301
     * @param mDBGroupName {String} EMPLOYMENT STATUS
     * @param mDBGroupCode {String} DP0301
     * @param dP030001E {module:model/Acs5ProfilesValuesDP0301DP030001E} 
     * @param dP030002E {module:model/Acs5ProfilesValuesDP0301DP030002E} 
     * @param dP030002PE {module:model/Acs5ProfilesValuesDP0301DP030002PE} 
     * @param dP030004E {module:model/Acs5ProfilesValuesDP0301DP030004E} 
     * @param dP030004PE {module:model/Acs5ProfilesValuesDP0301DP030004PE} 
     * @param dP030005E {module:model/Acs5ProfilesValuesDP0301DP030005E} 
     * @param dP030005PE {module:model/Acs5ProfilesValuesDP0301DP030005PE} 
     * @param dP030006E {module:model/Acs5ProfilesValuesDP0301DP030006E} 
     * @param dP030006PE {module:model/Acs5ProfilesValuesDP0301DP030006PE} 
     * @param dP030007E {module:model/Acs5ProfilesValuesDP0301DP030007E} 
     * @param dP030007PE {module:model/Acs5ProfilesValuesDP0301DP030007PE} 
     * @param dP030008E {module:model/Acs5ProfilesValuesDP0301DP030008E} 
     * @param dP030008PE {module:model/Acs5ProfilesValuesDP0301DP030008PE} 
     * @param dP030009PE {module:model/Acs5ProfilesValuesDP0301DP030009PE} 
     * @param dP030010E {module:model/Acs5ProfilesValuesDP0301DP030010E} 
     * @param dP030010PE {module:model/Acs5ProfilesValuesDP0301DP030010PE} 
     * @param dP030014E {module:model/Acs5ProfilesValuesDP0301DP030014E} 
     * @param dP030014PE {module:model/Acs5ProfilesValuesDP0301DP030014PE} 
     * @param dP030016E {module:model/Acs5ProfilesValuesDP0301DP030016E} 
     * @param dP030016PE {module:model/Acs5ProfilesValuesDP0301DP030016PE} 
     */
    constructor(mDBGroupName, mDBGroupCode, dP030001E, dP030002E, dP030002PE, dP030004E, dP030004PE, dP030005E, dP030005PE, dP030006E, dP030006PE, dP030007E, dP030007PE, dP030008E, dP030008PE, dP030009PE, dP030010E, dP030010PE, dP030014E, dP030014PE, dP030016E, dP030016PE) { 
        
        Acs5ProfilesValuesDP0301.initialize(this, mDBGroupName, mDBGroupCode, dP030001E, dP030002E, dP030002PE, dP030004E, dP030004PE, dP030005E, dP030005PE, dP030006E, dP030006PE, dP030007E, dP030007PE, dP030008E, dP030008PE, dP030009PE, dP030010E, dP030010PE, dP030014E, dP030014PE, dP030016E, dP030016PE);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, mDBGroupName, mDBGroupCode, dP030001E, dP030002E, dP030002PE, dP030004E, dP030004PE, dP030005E, dP030005PE, dP030006E, dP030006PE, dP030007E, dP030007PE, dP030008E, dP030008PE, dP030009PE, dP030010E, dP030010PE, dP030014E, dP030014PE, dP030016E, dP030016PE) { 
        obj['MDBGroupName'] = mDBGroupName;
        obj['MDBGroupCode'] = mDBGroupCode;
        obj['DP030001E'] = dP030001E;
        obj['DP030002E'] = dP030002E;
        obj['DP030002PE'] = dP030002PE;
        obj['DP030004E'] = dP030004E;
        obj['DP030004PE'] = dP030004PE;
        obj['DP030005E'] = dP030005E;
        obj['DP030005PE'] = dP030005PE;
        obj['DP030006E'] = dP030006E;
        obj['DP030006PE'] = dP030006PE;
        obj['DP030007E'] = dP030007E;
        obj['DP030007PE'] = dP030007PE;
        obj['DP030008E'] = dP030008E;
        obj['DP030008PE'] = dP030008PE;
        obj['DP030009PE'] = dP030009PE;
        obj['DP030010E'] = dP030010E;
        obj['DP030010PE'] = dP030010PE;
        obj['DP030014E'] = dP030014E;
        obj['DP030014PE'] = dP030014PE;
        obj['DP030016E'] = dP030016E;
        obj['DP030016PE'] = dP030016PE;
    }

    /**
     * Constructs a <code>Acs5ProfilesValuesDP0301</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Acs5ProfilesValuesDP0301} obj Optional instance to populate.
     * @return {module:model/Acs5ProfilesValuesDP0301} The populated <code>Acs5ProfilesValuesDP0301</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Acs5ProfilesValuesDP0301();

            if (data.hasOwnProperty('MDBGroupName')) {
                obj['MDBGroupName'] = ApiClient.convertToType(data['MDBGroupName'], 'String');
            }
            if (data.hasOwnProperty('MDBGroupCode')) {
                obj['MDBGroupCode'] = ApiClient.convertToType(data['MDBGroupCode'], 'String');
            }
            if (data.hasOwnProperty('DP030001E')) {
                obj['DP030001E'] = Acs5ProfilesValuesDP0301DP030001E.constructFromObject(data['DP030001E']);
            }
            if (data.hasOwnProperty('DP030002E')) {
                obj['DP030002E'] = Acs5ProfilesValuesDP0301DP030002E.constructFromObject(data['DP030002E']);
            }
            if (data.hasOwnProperty('DP030002PE')) {
                obj['DP030002PE'] = Acs5ProfilesValuesDP0301DP030002PE.constructFromObject(data['DP030002PE']);
            }
            if (data.hasOwnProperty('DP030004E')) {
                obj['DP030004E'] = Acs5ProfilesValuesDP0301DP030004E.constructFromObject(data['DP030004E']);
            }
            if (data.hasOwnProperty('DP030004PE')) {
                obj['DP030004PE'] = Acs5ProfilesValuesDP0301DP030004PE.constructFromObject(data['DP030004PE']);
            }
            if (data.hasOwnProperty('DP030005E')) {
                obj['DP030005E'] = Acs5ProfilesValuesDP0301DP030005E.constructFromObject(data['DP030005E']);
            }
            if (data.hasOwnProperty('DP030005PE')) {
                obj['DP030005PE'] = Acs5ProfilesValuesDP0301DP030005PE.constructFromObject(data['DP030005PE']);
            }
            if (data.hasOwnProperty('DP030006E')) {
                obj['DP030006E'] = Acs5ProfilesValuesDP0301DP030006E.constructFromObject(data['DP030006E']);
            }
            if (data.hasOwnProperty('DP030006PE')) {
                obj['DP030006PE'] = Acs5ProfilesValuesDP0301DP030006PE.constructFromObject(data['DP030006PE']);
            }
            if (data.hasOwnProperty('DP030007E')) {
                obj['DP030007E'] = Acs5ProfilesValuesDP0301DP030007E.constructFromObject(data['DP030007E']);
            }
            if (data.hasOwnProperty('DP030007PE')) {
                obj['DP030007PE'] = Acs5ProfilesValuesDP0301DP030007PE.constructFromObject(data['DP030007PE']);
            }
            if (data.hasOwnProperty('DP030008E')) {
                obj['DP030008E'] = Acs5ProfilesValuesDP0301DP030008E.constructFromObject(data['DP030008E']);
            }
            if (data.hasOwnProperty('DP030008PE')) {
                obj['DP030008PE'] = Acs5ProfilesValuesDP0301DP030008PE.constructFromObject(data['DP030008PE']);
            }
            if (data.hasOwnProperty('DP030009PE')) {
                obj['DP030009PE'] = Acs5ProfilesValuesDP0301DP030009PE.constructFromObject(data['DP030009PE']);
            }
            if (data.hasOwnProperty('DP030010E')) {
                obj['DP030010E'] = Acs5ProfilesValuesDP0301DP030010E.constructFromObject(data['DP030010E']);
            }
            if (data.hasOwnProperty('DP030010PE')) {
                obj['DP030010PE'] = Acs5ProfilesValuesDP0301DP030010PE.constructFromObject(data['DP030010PE']);
            }
            if (data.hasOwnProperty('DP030014E')) {
                obj['DP030014E'] = Acs5ProfilesValuesDP0301DP030014E.constructFromObject(data['DP030014E']);
            }
            if (data.hasOwnProperty('DP030014PE')) {
                obj['DP030014PE'] = Acs5ProfilesValuesDP0301DP030014PE.constructFromObject(data['DP030014PE']);
            }
            if (data.hasOwnProperty('DP030016E')) {
                obj['DP030016E'] = Acs5ProfilesValuesDP0301DP030016E.constructFromObject(data['DP030016E']);
            }
            if (data.hasOwnProperty('DP030016PE')) {
                obj['DP030016PE'] = Acs5ProfilesValuesDP0301DP030016PE.constructFromObject(data['DP030016PE']);
            }
        }
        return obj;
    }


}

/**
 * EMPLOYMENT STATUS
 * @member {String} MDBGroupName
 */
Acs5ProfilesValuesDP0301.prototype['MDBGroupName'] = undefined;

/**
 * DP0301
 * @member {String} MDBGroupCode
 */
Acs5ProfilesValuesDP0301.prototype['MDBGroupCode'] = undefined;

/**
 * @member {module:model/Acs5ProfilesValuesDP0301DP030001E} DP030001E
 */
Acs5ProfilesValuesDP0301.prototype['DP030001E'] = undefined;

/**
 * @member {module:model/Acs5ProfilesValuesDP0301DP030002E} DP030002E
 */
Acs5ProfilesValuesDP0301.prototype['DP030002E'] = undefined;

/**
 * @member {module:model/Acs5ProfilesValuesDP0301DP030002PE} DP030002PE
 */
Acs5ProfilesValuesDP0301.prototype['DP030002PE'] = undefined;

/**
 * @member {module:model/Acs5ProfilesValuesDP0301DP030004E} DP030004E
 */
Acs5ProfilesValuesDP0301.prototype['DP030004E'] = undefined;

/**
 * @member {module:model/Acs5ProfilesValuesDP0301DP030004PE} DP030004PE
 */
Acs5ProfilesValuesDP0301.prototype['DP030004PE'] = undefined;

/**
 * @member {module:model/Acs5ProfilesValuesDP0301DP030005E} DP030005E
 */
Acs5ProfilesValuesDP0301.prototype['DP030005E'] = undefined;

/**
 * @member {module:model/Acs5ProfilesValuesDP0301DP030005PE} DP030005PE
 */
Acs5ProfilesValuesDP0301.prototype['DP030005PE'] = undefined;

/**
 * @member {module:model/Acs5ProfilesValuesDP0301DP030006E} DP030006E
 */
Acs5ProfilesValuesDP0301.prototype['DP030006E'] = undefined;

/**
 * @member {module:model/Acs5ProfilesValuesDP0301DP030006PE} DP030006PE
 */
Acs5ProfilesValuesDP0301.prototype['DP030006PE'] = undefined;

/**
 * @member {module:model/Acs5ProfilesValuesDP0301DP030007E} DP030007E
 */
Acs5ProfilesValuesDP0301.prototype['DP030007E'] = undefined;

/**
 * @member {module:model/Acs5ProfilesValuesDP0301DP030007PE} DP030007PE
 */
Acs5ProfilesValuesDP0301.prototype['DP030007PE'] = undefined;

/**
 * @member {module:model/Acs5ProfilesValuesDP0301DP030008E} DP030008E
 */
Acs5ProfilesValuesDP0301.prototype['DP030008E'] = undefined;

/**
 * @member {module:model/Acs5ProfilesValuesDP0301DP030008PE} DP030008PE
 */
Acs5ProfilesValuesDP0301.prototype['DP030008PE'] = undefined;

/**
 * @member {module:model/Acs5ProfilesValuesDP0301DP030009PE} DP030009PE
 */
Acs5ProfilesValuesDP0301.prototype['DP030009PE'] = undefined;

/**
 * @member {module:model/Acs5ProfilesValuesDP0301DP030010E} DP030010E
 */
Acs5ProfilesValuesDP0301.prototype['DP030010E'] = undefined;

/**
 * @member {module:model/Acs5ProfilesValuesDP0301DP030010PE} DP030010PE
 */
Acs5ProfilesValuesDP0301.prototype['DP030010PE'] = undefined;

/**
 * @member {module:model/Acs5ProfilesValuesDP0301DP030014E} DP030014E
 */
Acs5ProfilesValuesDP0301.prototype['DP030014E'] = undefined;

/**
 * @member {module:model/Acs5ProfilesValuesDP0301DP030014PE} DP030014PE
 */
Acs5ProfilesValuesDP0301.prototype['DP030014PE'] = undefined;

/**
 * @member {module:model/Acs5ProfilesValuesDP0301DP030016E} DP030016E
 */
Acs5ProfilesValuesDP0301.prototype['DP030016E'] = undefined;

/**
 * @member {module:model/Acs5ProfilesValuesDP0301DP030016PE} DP030016PE
 */
Acs5ProfilesValuesDP0301.prototype['DP030016PE'] = undefined;






export default Acs5ProfilesValuesDP0301;

