/**
 * Geo Spatial Query Api - US Census Boundaries and Census Data
 * Easily integrate geospatial point-in-polygon search, census boundaries, location-based data, geofencing, and other location-based features into web and mobile apps. SDK Our Software Development Kit (SDK) is available on GitHub at https://github.com/geospatialqueryapi/geospatialqueryapi-sdk. If possible then we are strongly recommending using our tested libraries available on GitHub, rather than creating new ones.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mobiledatabooks@mobiledatabooks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Acs5ProfilesValuesDP0505DP050070E from './Acs5ProfilesValuesDP0505DP050070E';
import Acs5ProfilesValuesDP0505DP050071E from './Acs5ProfilesValuesDP0505DP050071E';
import Acs5ProfilesValuesDP0505DP050071PE from './Acs5ProfilesValuesDP0505DP050071PE';
import Acs5ProfilesValuesDP0505DP050076E from './Acs5ProfilesValuesDP0505DP050076E';
import Acs5ProfilesValuesDP0505DP050076PE from './Acs5ProfilesValuesDP0505DP050076PE';
import Acs5ProfilesValuesDP0505DP050077E from './Acs5ProfilesValuesDP0505DP050077E';
import Acs5ProfilesValuesDP0505DP050077PE from './Acs5ProfilesValuesDP0505DP050077PE';
import Acs5ProfilesValuesDP0505DP050083E from './Acs5ProfilesValuesDP0505DP050083E';
import Acs5ProfilesValuesDP0505DP050083PE from './Acs5ProfilesValuesDP0505DP050083PE';

/**
 * The Acs5ProfilesValuesDP0505 model module.
 * @module model/Acs5ProfilesValuesDP0505
 * @version 1.0.0
 */
class Acs5ProfilesValuesDP0505 {
    /**
     * Constructs a new <code>Acs5ProfilesValuesDP0505</code>.
     * @alias module:model/Acs5ProfilesValuesDP0505
     * @param mDBGroupName {String} 
     * @param mDBGroupCode {String} 
     * @param dP050070E {module:model/Acs5ProfilesValuesDP0505DP050070E} 
     * @param dP050071E {module:model/Acs5ProfilesValuesDP0505DP050071E} 
     * @param dP050071PE {module:model/Acs5ProfilesValuesDP0505DP050071PE} 
     * @param dP050076E {module:model/Acs5ProfilesValuesDP0505DP050076E} 
     * @param dP050076PE {module:model/Acs5ProfilesValuesDP0505DP050076PE} 
     * @param dP050077E {module:model/Acs5ProfilesValuesDP0505DP050077E} 
     * @param dP050077PE {module:model/Acs5ProfilesValuesDP0505DP050077PE} 
     * @param dP050083E {module:model/Acs5ProfilesValuesDP0505DP050083E} 
     * @param dP050083PE {module:model/Acs5ProfilesValuesDP0505DP050083PE} 
     */
    constructor(mDBGroupName, mDBGroupCode, dP050070E, dP050071E, dP050071PE, dP050076E, dP050076PE, dP050077E, dP050077PE, dP050083E, dP050083PE) { 
        
        Acs5ProfilesValuesDP0505.initialize(this, mDBGroupName, mDBGroupCode, dP050070E, dP050071E, dP050071PE, dP050076E, dP050076PE, dP050077E, dP050077PE, dP050083E, dP050083PE);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, mDBGroupName, mDBGroupCode, dP050070E, dP050071E, dP050071PE, dP050076E, dP050076PE, dP050077E, dP050077PE, dP050083E, dP050083PE) { 
        obj['MDBGroupName'] = mDBGroupName;
        obj['MDBGroupCode'] = mDBGroupCode;
        obj['DP050070E'] = dP050070E;
        obj['DP050071E'] = dP050071E;
        obj['DP050071PE'] = dP050071PE;
        obj['DP050076E'] = dP050076E;
        obj['DP050076PE'] = dP050076PE;
        obj['DP050077E'] = dP050077E;
        obj['DP050077PE'] = dP050077PE;
        obj['DP050083E'] = dP050083E;
        obj['DP050083PE'] = dP050083PE;
    }

    /**
     * Constructs a <code>Acs5ProfilesValuesDP0505</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Acs5ProfilesValuesDP0505} obj Optional instance to populate.
     * @return {module:model/Acs5ProfilesValuesDP0505} The populated <code>Acs5ProfilesValuesDP0505</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Acs5ProfilesValuesDP0505();

            if (data.hasOwnProperty('MDBGroupName')) {
                obj['MDBGroupName'] = ApiClient.convertToType(data['MDBGroupName'], 'String');
            }
            if (data.hasOwnProperty('MDBGroupCode')) {
                obj['MDBGroupCode'] = ApiClient.convertToType(data['MDBGroupCode'], 'String');
            }
            if (data.hasOwnProperty('DP050070E')) {
                obj['DP050070E'] = Acs5ProfilesValuesDP0505DP050070E.constructFromObject(data['DP050070E']);
            }
            if (data.hasOwnProperty('DP050071E')) {
                obj['DP050071E'] = Acs5ProfilesValuesDP0505DP050071E.constructFromObject(data['DP050071E']);
            }
            if (data.hasOwnProperty('DP050071PE')) {
                obj['DP050071PE'] = Acs5ProfilesValuesDP0505DP050071PE.constructFromObject(data['DP050071PE']);
            }
            if (data.hasOwnProperty('DP050076E')) {
                obj['DP050076E'] = Acs5ProfilesValuesDP0505DP050076E.constructFromObject(data['DP050076E']);
            }
            if (data.hasOwnProperty('DP050076PE')) {
                obj['DP050076PE'] = Acs5ProfilesValuesDP0505DP050076PE.constructFromObject(data['DP050076PE']);
            }
            if (data.hasOwnProperty('DP050077E')) {
                obj['DP050077E'] = Acs5ProfilesValuesDP0505DP050077E.constructFromObject(data['DP050077E']);
            }
            if (data.hasOwnProperty('DP050077PE')) {
                obj['DP050077PE'] = Acs5ProfilesValuesDP0505DP050077PE.constructFromObject(data['DP050077PE']);
            }
            if (data.hasOwnProperty('DP050083E')) {
                obj['DP050083E'] = Acs5ProfilesValuesDP0505DP050083E.constructFromObject(data['DP050083E']);
            }
            if (data.hasOwnProperty('DP050083PE')) {
                obj['DP050083PE'] = Acs5ProfilesValuesDP0505DP050083PE.constructFromObject(data['DP050083PE']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} MDBGroupName
 */
Acs5ProfilesValuesDP0505.prototype['MDBGroupName'] = undefined;

/**
 * @member {String} MDBGroupCode
 */
Acs5ProfilesValuesDP0505.prototype['MDBGroupCode'] = undefined;

/**
 * @member {module:model/Acs5ProfilesValuesDP0505DP050070E} DP050070E
 */
Acs5ProfilesValuesDP0505.prototype['DP050070E'] = undefined;

/**
 * @member {module:model/Acs5ProfilesValuesDP0505DP050071E} DP050071E
 */
Acs5ProfilesValuesDP0505.prototype['DP050071E'] = undefined;

/**
 * @member {module:model/Acs5ProfilesValuesDP0505DP050071PE} DP050071PE
 */
Acs5ProfilesValuesDP0505.prototype['DP050071PE'] = undefined;

/**
 * @member {module:model/Acs5ProfilesValuesDP0505DP050076E} DP050076E
 */
Acs5ProfilesValuesDP0505.prototype['DP050076E'] = undefined;

/**
 * @member {module:model/Acs5ProfilesValuesDP0505DP050076PE} DP050076PE
 */
Acs5ProfilesValuesDP0505.prototype['DP050076PE'] = undefined;

/**
 * @member {module:model/Acs5ProfilesValuesDP0505DP050077E} DP050077E
 */
Acs5ProfilesValuesDP0505.prototype['DP050077E'] = undefined;

/**
 * @member {module:model/Acs5ProfilesValuesDP0505DP050077PE} DP050077PE
 */
Acs5ProfilesValuesDP0505.prototype['DP050077PE'] = undefined;

/**
 * @member {module:model/Acs5ProfilesValuesDP0505DP050083E} DP050083E
 */
Acs5ProfilesValuesDP0505.prototype['DP050083E'] = undefined;

/**
 * @member {module:model/Acs5ProfilesValuesDP0505DP050083PE} DP050083PE
 */
Acs5ProfilesValuesDP0505.prototype['DP050083PE'] = undefined;






export default Acs5ProfilesValuesDP0505;

