//
// Acs5ProfilesValuesDP0306.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** INCOME AND BENEFITS (IN 2010 INFLATION-ADJUSTED DOLLARS) */
public struct Acs5ProfilesValuesDP0306: Codable, Hashable {

    /** INCOME AND BENEFITS (IN 2010 INFLATION-ADJUSTED DOLLARS) */
    public var mDBGroupName: String
    /** DP0306 */
    public var mDBGroupCode: String
    public var dP030051E: Acs5ProfilesValuesDP0306DP030051E
    public var dP030052E: Acs5ProfilesValuesDP0306DP030052E
    public var dP030052PE: Acs5ProfilesValuesDP0306DP030052PE
    public var dP030053E: Acs5ProfilesValuesDP0306DP030053E
    public var dP030053PE: Acs5ProfilesValuesDP0306DP030053PE
    public var dP030054E: Acs5ProfilesValuesDP0306DP030054E
    public var dP030054PE: Acs5ProfilesValuesDP0306DP030054PE
    public var dP030055E: Acs5ProfilesValuesDP0306DP030055E
    public var dP030055PE: Acs5ProfilesValuesDP0306DP030055PE
    public var dP030056E: Acs5ProfilesValuesDP0306DP030056E
    public var dP030056PE: Acs5ProfilesValuesDP0306DP030056PE
    public var dP030057E: Acs5ProfilesValuesDP0306DP030057E
    public var dP030057PE: Acs5ProfilesValuesDP0306DP030057PE
    public var dP030058E: Acs5ProfilesValuesDP0306DP030058E
    public var dP030058PE: Acs5ProfilesValuesDP0306DP030058PE
    public var dP030059E: Acs5ProfilesValuesDP0306DP030059E
    public var dP030059PE: Acs5ProfilesValuesDP0306DP030059PE
    public var dP030060E: Acs5ProfilesValuesDP0306DP030060E
    public var dP030060PE: Acs5ProfilesValuesDP0306DP030060PE
    public var dP030061E: Acs5ProfilesValuesDP0306DP030061E
    public var dP030061PE: Acs5ProfilesValuesDP0306DP030061PE
    public var dP030062E: Acs5ProfilesValuesDP0306DP030062E
    public var dP030063E: Acs5ProfilesValuesDP0306DP030063E
    public var dP030086E: Acs5ProfilesValuesDP0306DP030086E
    public var dP030087E: Acs5ProfilesValuesDP0306DP030087E
    public var dP030088E: Acs5ProfilesValuesDP0306DP030088E

    public init(mDBGroupName: String, mDBGroupCode: String, dP030051E: Acs5ProfilesValuesDP0306DP030051E, dP030052E: Acs5ProfilesValuesDP0306DP030052E, dP030052PE: Acs5ProfilesValuesDP0306DP030052PE, dP030053E: Acs5ProfilesValuesDP0306DP030053E, dP030053PE: Acs5ProfilesValuesDP0306DP030053PE, dP030054E: Acs5ProfilesValuesDP0306DP030054E, dP030054PE: Acs5ProfilesValuesDP0306DP030054PE, dP030055E: Acs5ProfilesValuesDP0306DP030055E, dP030055PE: Acs5ProfilesValuesDP0306DP030055PE, dP030056E: Acs5ProfilesValuesDP0306DP030056E, dP030056PE: Acs5ProfilesValuesDP0306DP030056PE, dP030057E: Acs5ProfilesValuesDP0306DP030057E, dP030057PE: Acs5ProfilesValuesDP0306DP030057PE, dP030058E: Acs5ProfilesValuesDP0306DP030058E, dP030058PE: Acs5ProfilesValuesDP0306DP030058PE, dP030059E: Acs5ProfilesValuesDP0306DP030059E, dP030059PE: Acs5ProfilesValuesDP0306DP030059PE, dP030060E: Acs5ProfilesValuesDP0306DP030060E, dP030060PE: Acs5ProfilesValuesDP0306DP030060PE, dP030061E: Acs5ProfilesValuesDP0306DP030061E, dP030061PE: Acs5ProfilesValuesDP0306DP030061PE, dP030062E: Acs5ProfilesValuesDP0306DP030062E, dP030063E: Acs5ProfilesValuesDP0306DP030063E, dP030086E: Acs5ProfilesValuesDP0306DP030086E, dP030087E: Acs5ProfilesValuesDP0306DP030087E, dP030088E: Acs5ProfilesValuesDP0306DP030088E) {
        self.mDBGroupName = mDBGroupName
        self.mDBGroupCode = mDBGroupCode
        self.dP030051E = dP030051E
        self.dP030052E = dP030052E
        self.dP030052PE = dP030052PE
        self.dP030053E = dP030053E
        self.dP030053PE = dP030053PE
        self.dP030054E = dP030054E
        self.dP030054PE = dP030054PE
        self.dP030055E = dP030055E
        self.dP030055PE = dP030055PE
        self.dP030056E = dP030056E
        self.dP030056PE = dP030056PE
        self.dP030057E = dP030057E
        self.dP030057PE = dP030057PE
        self.dP030058E = dP030058E
        self.dP030058PE = dP030058PE
        self.dP030059E = dP030059E
        self.dP030059PE = dP030059PE
        self.dP030060E = dP030060E
        self.dP030060PE = dP030060PE
        self.dP030061E = dP030061E
        self.dP030061PE = dP030061PE
        self.dP030062E = dP030062E
        self.dP030063E = dP030063E
        self.dP030086E = dP030086E
        self.dP030087E = dP030087E
        self.dP030088E = dP030088E
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case mDBGroupName = "MDBGroupName"
        case mDBGroupCode = "MDBGroupCode"
        case dP030051E = "DP030051E"
        case dP030052E = "DP030052E"
        case dP030052PE = "DP030052PE"
        case dP030053E = "DP030053E"
        case dP030053PE = "DP030053PE"
        case dP030054E = "DP030054E"
        case dP030054PE = "DP030054PE"
        case dP030055E = "DP030055E"
        case dP030055PE = "DP030055PE"
        case dP030056E = "DP030056E"
        case dP030056PE = "DP030056PE"
        case dP030057E = "DP030057E"
        case dP030057PE = "DP030057PE"
        case dP030058E = "DP030058E"
        case dP030058PE = "DP030058PE"
        case dP030059E = "DP030059E"
        case dP030059PE = "DP030059PE"
        case dP030060E = "DP030060E"
        case dP030060PE = "DP030060PE"
        case dP030061E = "DP030061E"
        case dP030061PE = "DP030061PE"
        case dP030062E = "DP030062E"
        case dP030063E = "DP030063E"
        case dP030086E = "DP030086E"
        case dP030087E = "DP030087E"
        case dP030088E = "DP030088E"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(mDBGroupName, forKey: .mDBGroupName)
        try container.encode(mDBGroupCode, forKey: .mDBGroupCode)
        try container.encode(dP030051E, forKey: .dP030051E)
        try container.encode(dP030052E, forKey: .dP030052E)
        try container.encode(dP030052PE, forKey: .dP030052PE)
        try container.encode(dP030053E, forKey: .dP030053E)
        try container.encode(dP030053PE, forKey: .dP030053PE)
        try container.encode(dP030054E, forKey: .dP030054E)
        try container.encode(dP030054PE, forKey: .dP030054PE)
        try container.encode(dP030055E, forKey: .dP030055E)
        try container.encode(dP030055PE, forKey: .dP030055PE)
        try container.encode(dP030056E, forKey: .dP030056E)
        try container.encode(dP030056PE, forKey: .dP030056PE)
        try container.encode(dP030057E, forKey: .dP030057E)
        try container.encode(dP030057PE, forKey: .dP030057PE)
        try container.encode(dP030058E, forKey: .dP030058E)
        try container.encode(dP030058PE, forKey: .dP030058PE)
        try container.encode(dP030059E, forKey: .dP030059E)
        try container.encode(dP030059PE, forKey: .dP030059PE)
        try container.encode(dP030060E, forKey: .dP030060E)
        try container.encode(dP030060PE, forKey: .dP030060PE)
        try container.encode(dP030061E, forKey: .dP030061E)
        try container.encode(dP030061PE, forKey: .dP030061PE)
        try container.encode(dP030062E, forKey: .dP030062E)
        try container.encode(dP030063E, forKey: .dP030063E)
        try container.encode(dP030086E, forKey: .dP030086E)
        try container.encode(dP030087E, forKey: .dP030087E)
        try container.encode(dP030088E, forKey: .dP030088E)
    }
}

