"""
    Geo Spatial Query Api - US Census Boundaries and Census Data

    Geospatial Query API: US Census Boundaries and Census Data  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: mobiledatabooks@mobiledatabooks.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.examples_api import ExamplesApi  # noqa: E501


class TestExamplesApi(unittest.TestCase):
    """ExamplesApi unit test stubs"""

    def setUp(self):
        self.api = ExamplesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_v1_boundaries_requests_uscounty_id_geoid(self):
        """Test case for get_v1_boundaries_requests_uscounty_id_geoid

        Your GET endpoint  # noqa: E501
        """
        pass

    def test_get_v1_boundaries_requests_uscousub_id_geoid(self):
        """Test case for get_v1_boundaries_requests_uscousub_id_geoid

        Your GET endpoint  # noqa: E501
        """
        pass

    def test_get_v1_boundaries_requests_usplace_id_geoid(self):
        """Test case for get_v1_boundaries_requests_usplace_id_geoid

        Your GET endpoint  # noqa: E501
        """
        pass

    def test_get_v1_boundaries_requests_usstate(self):
        """Test case for get_v1_boundaries_requests_usstate

        Your GET endpoint  # noqa: E501
        """
        pass

    def test_get_v1_boundaries_requests_ustract_id_geoid(self):
        """Test case for get_v1_boundaries_requests_ustract_id_geoid

        Your GET endpoint  # noqa: E501
        """
        pass

    def test_get_v1_boundaries_requests_zcta_id_geoid(self):
        """Test case for get_v1_boundaries_requests_zcta_id_geoid

        Your GET endpoint  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
