"""
    Geo Spatial Query Api - US Census Boundaries and Census Data

    Geospatial Query API: US Census Boundaries and Census Data  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: mobiledatabooks@mobiledatabooks.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.acs5_profiles_values_dp0203_dp020031_pe import Acs5ProfilesValuesDP0203DP020031PE


class TestAcs5ProfilesValuesDP0203DP020031PE(unittest.TestCase):
    """Acs5ProfilesValuesDP0203DP020031PE unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAcs5ProfilesValuesDP0203DP020031PE(self):
        """Test Acs5ProfilesValuesDP0203DP020031PE"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Acs5ProfilesValuesDP0203DP020031PE()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
