"""
    Geo Spatial Query Api - US Census Boundaries and Census Data

    Easily integrate geospatial point-in-polygon search, census boundaries, location-based data, geofencing, and other location-based features into web and mobile apps. Our Software Development Kit (SDK) is available on GitHub at https://github.com/geospatialqueryapi/geospatialqueryapi-sdk. If possible then we are strongly recommending using our tested libraries available on GitHub, rather than creating new ones.      Copyright © 2021 Mobile Data Books, LLC. All Rights Reserved.    # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: mobiledatabooks@mobiledatabooks.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.acs5_profiles_values_dp0410_dp040090_e import Acs5ProfilesValuesDP0410DP040090E
from openapi_client.model.acs5_profiles_values_dp0410_dp040090_pe import Acs5ProfilesValuesDP0410DP040090PE
from openapi_client.model.acs5_profiles_values_dp0410_dp040091_e import Acs5ProfilesValuesDP0410DP040091E
from openapi_client.model.acs5_profiles_values_dp0410_dp040091_pe import Acs5ProfilesValuesDP0410DP040091PE
from openapi_client.model.acs5_profiles_values_dp0410_dp040092_e import Acs5ProfilesValuesDP0410DP040092E
from openapi_client.model.acs5_profiles_values_dp0410_dp040092_pe import Acs5ProfilesValuesDP0410DP040092PE
from openapi_client.model.acs5_profiles_values_dp0410_dp040093_e import Acs5ProfilesValuesDP0410DP040093E
globals()['Acs5ProfilesValuesDP0410DP040090E'] = Acs5ProfilesValuesDP0410DP040090E
globals()['Acs5ProfilesValuesDP0410DP040090PE'] = Acs5ProfilesValuesDP0410DP040090PE
globals()['Acs5ProfilesValuesDP0410DP040091E'] = Acs5ProfilesValuesDP0410DP040091E
globals()['Acs5ProfilesValuesDP0410DP040091PE'] = Acs5ProfilesValuesDP0410DP040091PE
globals()['Acs5ProfilesValuesDP0410DP040092E'] = Acs5ProfilesValuesDP0410DP040092E
globals()['Acs5ProfilesValuesDP0410DP040092PE'] = Acs5ProfilesValuesDP0410DP040092PE
globals()['Acs5ProfilesValuesDP0410DP040093E'] = Acs5ProfilesValuesDP0410DP040093E
from openapi_client.model.acs5_profiles_values_dp0410 import Acs5ProfilesValuesDP0410


class TestAcs5ProfilesValuesDP0410(unittest.TestCase):
    """Acs5ProfilesValuesDP0410 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAcs5ProfilesValuesDP0410(self):
        """Test Acs5ProfilesValuesDP0410"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Acs5ProfilesValuesDP0410()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
