"""
    Geo Spatial Query Api - US Census Boundaries and Census Data

    Geospatial Query API: US Census Boundaries and Census Data /doc.html  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: mobiledatabooks@mobiledatabooks.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.acs5_profiles_values_dp0204_dp020037_e import Acs5ProfilesValuesDP0204DP020037E
from openapi_client.model.acs5_profiles_values_dp0204_dp020037_pe import Acs5ProfilesValuesDP0204DP020037PE
from openapi_client.model.acs5_profiles_values_dp0204_dp020038_e import Acs5ProfilesValuesDP0204DP020038E
from openapi_client.model.acs5_profiles_values_dp0204_dp020038_pe import Acs5ProfilesValuesDP0204DP020038PE
from openapi_client.model.acs5_profiles_values_dp0204_dp020040_e import Acs5ProfilesValuesDP0204DP020040E
globals()['Acs5ProfilesValuesDP0204DP020037E'] = Acs5ProfilesValuesDP0204DP020037E
globals()['Acs5ProfilesValuesDP0204DP020037PE'] = Acs5ProfilesValuesDP0204DP020037PE
globals()['Acs5ProfilesValuesDP0204DP020038E'] = Acs5ProfilesValuesDP0204DP020038E
globals()['Acs5ProfilesValuesDP0204DP020038PE'] = Acs5ProfilesValuesDP0204DP020038PE
globals()['Acs5ProfilesValuesDP0204DP020040E'] = Acs5ProfilesValuesDP0204DP020040E
from openapi_client.model.acs5_profiles_values_dp0204 import Acs5ProfilesValuesDP0204


class TestAcs5ProfilesValuesDP0204(unittest.TestCase):
    """Acs5ProfilesValuesDP0204 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAcs5ProfilesValuesDP0204(self):
        """Test Acs5ProfilesValuesDP0204"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Acs5ProfilesValuesDP0204()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
