"""
    Geo Spatial Query Api - US Census Boundaries and Census Data

    Easily integrate geospatial point-in-polygon search, census boundaries, location-based data, geofencing, and other location-based features into web and mobile apps. Our Software Development Kit (SDK) is available on GitHub at https://github.com/geospatialqueryapi/geospatialqueryapi-sdk. If possible then we are strongly recommending using our tested libraries available on GitHub, rather than creating new ones.      Copyright © 2021 Mobile Data Books, LLC. All Rights Reserved.    # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: mobiledatabooks@mobiledatabooks.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.examples_api import ExamplesApi  # noqa: E501


class TestExamplesApi(unittest.TestCase):
    """ExamplesApi unit test stubs"""

    def setUp(self):
        self.api = ExamplesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_v1_boundaries_requests_uscounty_id_geoid(self):
        """Test case for get_v1_boundaries_requests_uscounty_id_geoid

        v1-boundaries-requests-uscounty-id-GEOID  # noqa: E501
        """
        pass

    def test_get_v1_boundaries_requests_uscousub_id_geoid(self):
        """Test case for get_v1_boundaries_requests_uscousub_id_geoid

        v1-boundaries-requests-uscousub-id-GEOID  # noqa: E501
        """
        pass

    def test_get_v1_boundaries_requests_usplace_id_geoid(self):
        """Test case for get_v1_boundaries_requests_usplace_id_geoid

        v1-boundaries-requests-usplace-id-GEOID  # noqa: E501
        """
        pass

    def test_get_v1_boundaries_requests_usstate(self):
        """Test case for get_v1_boundaries_requests_usstate

        v1-boundaries-requests-usstate  # noqa: E501
        """
        pass

    def test_get_v1_boundaries_requests_ustract_id_geoid(self):
        """Test case for get_v1_boundaries_requests_ustract_id_geoid

        v1-boundaries-requests-ustract-id-GEOID  # noqa: E501
        """
        pass

    def test_get_v1_boundaries_requests_zcta_id_geoid(self):
        """Test case for get_v1_boundaries_requests_zcta_id_geoid

        v1-boundaries-requests-zcta-id-GEOID  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
