"""
    Geo Spatial Query Api - US Census Boundaries and Census Data

    Easily integrate geospatial point-in-polygon search, census boundaries, location-based data, geofencing, and other location-based features into web and mobile apps. SDK Our Software Development Kit (SDK) is available on GitHub at https://github.com/geospatialqueryapi/geospatialqueryapi-sdk. If possible then we are strongly recommending using our tested libraries available on GitHub, rather than creating new ones.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: mobiledatabooks@mobiledatabooks.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.acs5_profiles_values_dp0301_dp030001_e import Acs5ProfilesValuesDP0301DP030001E
from openapi_client.model.acs5_profiles_values_dp0301_dp030002_e import Acs5ProfilesValuesDP0301DP030002E
from openapi_client.model.acs5_profiles_values_dp0301_dp030002_pe import Acs5ProfilesValuesDP0301DP030002PE
from openapi_client.model.acs5_profiles_values_dp0301_dp030004_e import Acs5ProfilesValuesDP0301DP030004E
from openapi_client.model.acs5_profiles_values_dp0301_dp030004_pe import Acs5ProfilesValuesDP0301DP030004PE
from openapi_client.model.acs5_profiles_values_dp0301_dp030005_e import Acs5ProfilesValuesDP0301DP030005E
from openapi_client.model.acs5_profiles_values_dp0301_dp030005_pe import Acs5ProfilesValuesDP0301DP030005PE
from openapi_client.model.acs5_profiles_values_dp0301_dp030006_e import Acs5ProfilesValuesDP0301DP030006E
from openapi_client.model.acs5_profiles_values_dp0301_dp030006_pe import Acs5ProfilesValuesDP0301DP030006PE
from openapi_client.model.acs5_profiles_values_dp0301_dp030007_e import Acs5ProfilesValuesDP0301DP030007E
from openapi_client.model.acs5_profiles_values_dp0301_dp030007_pe import Acs5ProfilesValuesDP0301DP030007PE
from openapi_client.model.acs5_profiles_values_dp0301_dp030008_e import Acs5ProfilesValuesDP0301DP030008E
from openapi_client.model.acs5_profiles_values_dp0301_dp030008_pe import Acs5ProfilesValuesDP0301DP030008PE
from openapi_client.model.acs5_profiles_values_dp0301_dp030009_pe import Acs5ProfilesValuesDP0301DP030009PE
from openapi_client.model.acs5_profiles_values_dp0301_dp030010_e import Acs5ProfilesValuesDP0301DP030010E
from openapi_client.model.acs5_profiles_values_dp0301_dp030010_pe import Acs5ProfilesValuesDP0301DP030010PE
from openapi_client.model.acs5_profiles_values_dp0301_dp030014_e import Acs5ProfilesValuesDP0301DP030014E
from openapi_client.model.acs5_profiles_values_dp0301_dp030014_pe import Acs5ProfilesValuesDP0301DP030014PE
from openapi_client.model.acs5_profiles_values_dp0301_dp030016_e import Acs5ProfilesValuesDP0301DP030016E
from openapi_client.model.acs5_profiles_values_dp0301_dp030016_pe import Acs5ProfilesValuesDP0301DP030016PE
globals()['Acs5ProfilesValuesDP0301DP030001E'] = Acs5ProfilesValuesDP0301DP030001E
globals()['Acs5ProfilesValuesDP0301DP030002E'] = Acs5ProfilesValuesDP0301DP030002E
globals()['Acs5ProfilesValuesDP0301DP030002PE'] = Acs5ProfilesValuesDP0301DP030002PE
globals()['Acs5ProfilesValuesDP0301DP030004E'] = Acs5ProfilesValuesDP0301DP030004E
globals()['Acs5ProfilesValuesDP0301DP030004PE'] = Acs5ProfilesValuesDP0301DP030004PE
globals()['Acs5ProfilesValuesDP0301DP030005E'] = Acs5ProfilesValuesDP0301DP030005E
globals()['Acs5ProfilesValuesDP0301DP030005PE'] = Acs5ProfilesValuesDP0301DP030005PE
globals()['Acs5ProfilesValuesDP0301DP030006E'] = Acs5ProfilesValuesDP0301DP030006E
globals()['Acs5ProfilesValuesDP0301DP030006PE'] = Acs5ProfilesValuesDP0301DP030006PE
globals()['Acs5ProfilesValuesDP0301DP030007E'] = Acs5ProfilesValuesDP0301DP030007E
globals()['Acs5ProfilesValuesDP0301DP030007PE'] = Acs5ProfilesValuesDP0301DP030007PE
globals()['Acs5ProfilesValuesDP0301DP030008E'] = Acs5ProfilesValuesDP0301DP030008E
globals()['Acs5ProfilesValuesDP0301DP030008PE'] = Acs5ProfilesValuesDP0301DP030008PE
globals()['Acs5ProfilesValuesDP0301DP030009PE'] = Acs5ProfilesValuesDP0301DP030009PE
globals()['Acs5ProfilesValuesDP0301DP030010E'] = Acs5ProfilesValuesDP0301DP030010E
globals()['Acs5ProfilesValuesDP0301DP030010PE'] = Acs5ProfilesValuesDP0301DP030010PE
globals()['Acs5ProfilesValuesDP0301DP030014E'] = Acs5ProfilesValuesDP0301DP030014E
globals()['Acs5ProfilesValuesDP0301DP030014PE'] = Acs5ProfilesValuesDP0301DP030014PE
globals()['Acs5ProfilesValuesDP0301DP030016E'] = Acs5ProfilesValuesDP0301DP030016E
globals()['Acs5ProfilesValuesDP0301DP030016PE'] = Acs5ProfilesValuesDP0301DP030016PE
from openapi_client.model.acs5_profiles_values_dp0301 import Acs5ProfilesValuesDP0301


class TestAcs5ProfilesValuesDP0301(unittest.TestCase):
    """Acs5ProfilesValuesDP0301 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAcs5ProfilesValuesDP0301(self):
        """Test Acs5ProfilesValuesDP0301"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Acs5ProfilesValuesDP0301()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
