"""
    Geo Spatial Query Api - US Census Boundaries and Census Data

    Easily integrate geospatial point-in-polygon search, census boundaries, location-based data, geofencing, and other location-based features into web and mobile apps. Our Software Development Kit (SDK) is available on GitHub at https://github.com/geospatialqueryapi/geospatialqueryapi-sdk. If possible then we are strongly recommending using our tested libraries available on GitHub, rather than creating new ones.      Copyright © 2021 Mobile Data Books, LLC. All Rights Reserved.    # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: mobiledatabooks@mobiledatabooks.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.acs5_profiles_values_dp0503_dp050025_pe import Acs5ProfilesValuesDP0503DP050025PE


class TestAcs5ProfilesValuesDP0503DP050025PE(unittest.TestCase):
    """Acs5ProfilesValuesDP0503DP050025PE unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAcs5ProfilesValuesDP0503DP050025PE(self):
        """Test Acs5ProfilesValuesDP0503DP050025PE"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Acs5ProfilesValuesDP0503DP050025PE()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
