/*
 * Geo Spatial Query Api - US Census Boundaries and Census Data
 *
 * Geospatial Query API: US Census Boundaries and Census Data
 *
 * API version: 1.0.0
 * Contact: mobiledatabooks@mobiledatabooks.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// Acs5ProfilesValuesDP0406 struct for Acs5ProfilesValuesDP0406
type Acs5ProfilesValuesDP0406 struct {
	MDBGroupName string `json:"MDBGroupName"`
	MDBGroupCode string `json:"MDBGroupCode"`
	DP040045E Acs5ProfilesValuesDP0406DP040045E `json:"DP040045E"`
	DP040045PE Acs5ProfilesValuesDP0406DP040045PE `json:"DP040045PE"`
	DP040046E Acs5ProfilesValuesDP0406DP040046E `json:"DP040046E"`
	DP040046PE Acs5ProfilesValuesDP0406DP040046PE `json:"DP040046PE"`
	DP040047E Acs5ProfilesValuesDP0406DP040047E `json:"DP040047E"`
	DP040047PE Acs5ProfilesValuesDP0406DP040047PE `json:"DP040047PE"`
	DP040048E Acs5ProfilesValuesDP0406DP040048E `json:"DP040048E"`
	DP040049E Acs5ProfilesValuesDP0406DP040049E `json:"DP040049E"`
	AdditionalProperties map[string]interface{}
}

type _Acs5ProfilesValuesDP0406 Acs5ProfilesValuesDP0406

// NewAcs5ProfilesValuesDP0406 instantiates a new Acs5ProfilesValuesDP0406 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAcs5ProfilesValuesDP0406(mDBGroupName string, mDBGroupCode string, dP040045E Acs5ProfilesValuesDP0406DP040045E, dP040045PE Acs5ProfilesValuesDP0406DP040045PE, dP040046E Acs5ProfilesValuesDP0406DP040046E, dP040046PE Acs5ProfilesValuesDP0406DP040046PE, dP040047E Acs5ProfilesValuesDP0406DP040047E, dP040047PE Acs5ProfilesValuesDP0406DP040047PE, dP040048E Acs5ProfilesValuesDP0406DP040048E, dP040049E Acs5ProfilesValuesDP0406DP040049E) *Acs5ProfilesValuesDP0406 {
	this := Acs5ProfilesValuesDP0406{}
	this.MDBGroupName = mDBGroupName
	this.MDBGroupCode = mDBGroupCode
	this.DP040045E = dP040045E
	this.DP040045PE = dP040045PE
	this.DP040046E = dP040046E
	this.DP040046PE = dP040046PE
	this.DP040047E = dP040047E
	this.DP040047PE = dP040047PE
	this.DP040048E = dP040048E
	this.DP040049E = dP040049E
	return &this
}

// NewAcs5ProfilesValuesDP0406WithDefaults instantiates a new Acs5ProfilesValuesDP0406 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAcs5ProfilesValuesDP0406WithDefaults() *Acs5ProfilesValuesDP0406 {
	this := Acs5ProfilesValuesDP0406{}
	return &this
}

// GetMDBGroupName returns the MDBGroupName field value
func (o *Acs5ProfilesValuesDP0406) GetMDBGroupName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MDBGroupName
}

// GetMDBGroupNameOk returns a tuple with the MDBGroupName field value
// and a boolean to check if the value has been set.
func (o *Acs5ProfilesValuesDP0406) GetMDBGroupNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.MDBGroupName, true
}

// SetMDBGroupName sets field value
func (o *Acs5ProfilesValuesDP0406) SetMDBGroupName(v string) {
	o.MDBGroupName = v
}

// GetMDBGroupCode returns the MDBGroupCode field value
func (o *Acs5ProfilesValuesDP0406) GetMDBGroupCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MDBGroupCode
}

// GetMDBGroupCodeOk returns a tuple with the MDBGroupCode field value
// and a boolean to check if the value has been set.
func (o *Acs5ProfilesValuesDP0406) GetMDBGroupCodeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.MDBGroupCode, true
}

// SetMDBGroupCode sets field value
func (o *Acs5ProfilesValuesDP0406) SetMDBGroupCode(v string) {
	o.MDBGroupCode = v
}

// GetDP040045E returns the DP040045E field value
func (o *Acs5ProfilesValuesDP0406) GetDP040045E() Acs5ProfilesValuesDP0406DP040045E {
	if o == nil {
		var ret Acs5ProfilesValuesDP0406DP040045E
		return ret
	}

	return o.DP040045E
}

// GetDP040045EOk returns a tuple with the DP040045E field value
// and a boolean to check if the value has been set.
func (o *Acs5ProfilesValuesDP0406) GetDP040045EOk() (*Acs5ProfilesValuesDP0406DP040045E, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.DP040045E, true
}

// SetDP040045E sets field value
func (o *Acs5ProfilesValuesDP0406) SetDP040045E(v Acs5ProfilesValuesDP0406DP040045E) {
	o.DP040045E = v
}

// GetDP040045PE returns the DP040045PE field value
func (o *Acs5ProfilesValuesDP0406) GetDP040045PE() Acs5ProfilesValuesDP0406DP040045PE {
	if o == nil {
		var ret Acs5ProfilesValuesDP0406DP040045PE
		return ret
	}

	return o.DP040045PE
}

// GetDP040045PEOk returns a tuple with the DP040045PE field value
// and a boolean to check if the value has been set.
func (o *Acs5ProfilesValuesDP0406) GetDP040045PEOk() (*Acs5ProfilesValuesDP0406DP040045PE, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.DP040045PE, true
}

// SetDP040045PE sets field value
func (o *Acs5ProfilesValuesDP0406) SetDP040045PE(v Acs5ProfilesValuesDP0406DP040045PE) {
	o.DP040045PE = v
}

// GetDP040046E returns the DP040046E field value
func (o *Acs5ProfilesValuesDP0406) GetDP040046E() Acs5ProfilesValuesDP0406DP040046E {
	if o == nil {
		var ret Acs5ProfilesValuesDP0406DP040046E
		return ret
	}

	return o.DP040046E
}

// GetDP040046EOk returns a tuple with the DP040046E field value
// and a boolean to check if the value has been set.
func (o *Acs5ProfilesValuesDP0406) GetDP040046EOk() (*Acs5ProfilesValuesDP0406DP040046E, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.DP040046E, true
}

// SetDP040046E sets field value
func (o *Acs5ProfilesValuesDP0406) SetDP040046E(v Acs5ProfilesValuesDP0406DP040046E) {
	o.DP040046E = v
}

// GetDP040046PE returns the DP040046PE field value
func (o *Acs5ProfilesValuesDP0406) GetDP040046PE() Acs5ProfilesValuesDP0406DP040046PE {
	if o == nil {
		var ret Acs5ProfilesValuesDP0406DP040046PE
		return ret
	}

	return o.DP040046PE
}

// GetDP040046PEOk returns a tuple with the DP040046PE field value
// and a boolean to check if the value has been set.
func (o *Acs5ProfilesValuesDP0406) GetDP040046PEOk() (*Acs5ProfilesValuesDP0406DP040046PE, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.DP040046PE, true
}

// SetDP040046PE sets field value
func (o *Acs5ProfilesValuesDP0406) SetDP040046PE(v Acs5ProfilesValuesDP0406DP040046PE) {
	o.DP040046PE = v
}

// GetDP040047E returns the DP040047E field value
func (o *Acs5ProfilesValuesDP0406) GetDP040047E() Acs5ProfilesValuesDP0406DP040047E {
	if o == nil {
		var ret Acs5ProfilesValuesDP0406DP040047E
		return ret
	}

	return o.DP040047E
}

// GetDP040047EOk returns a tuple with the DP040047E field value
// and a boolean to check if the value has been set.
func (o *Acs5ProfilesValuesDP0406) GetDP040047EOk() (*Acs5ProfilesValuesDP0406DP040047E, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.DP040047E, true
}

// SetDP040047E sets field value
func (o *Acs5ProfilesValuesDP0406) SetDP040047E(v Acs5ProfilesValuesDP0406DP040047E) {
	o.DP040047E = v
}

// GetDP040047PE returns the DP040047PE field value
func (o *Acs5ProfilesValuesDP0406) GetDP040047PE() Acs5ProfilesValuesDP0406DP040047PE {
	if o == nil {
		var ret Acs5ProfilesValuesDP0406DP040047PE
		return ret
	}

	return o.DP040047PE
}

// GetDP040047PEOk returns a tuple with the DP040047PE field value
// and a boolean to check if the value has been set.
func (o *Acs5ProfilesValuesDP0406) GetDP040047PEOk() (*Acs5ProfilesValuesDP0406DP040047PE, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.DP040047PE, true
}

// SetDP040047PE sets field value
func (o *Acs5ProfilesValuesDP0406) SetDP040047PE(v Acs5ProfilesValuesDP0406DP040047PE) {
	o.DP040047PE = v
}

// GetDP040048E returns the DP040048E field value
func (o *Acs5ProfilesValuesDP0406) GetDP040048E() Acs5ProfilesValuesDP0406DP040048E {
	if o == nil {
		var ret Acs5ProfilesValuesDP0406DP040048E
		return ret
	}

	return o.DP040048E
}

// GetDP040048EOk returns a tuple with the DP040048E field value
// and a boolean to check if the value has been set.
func (o *Acs5ProfilesValuesDP0406) GetDP040048EOk() (*Acs5ProfilesValuesDP0406DP040048E, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.DP040048E, true
}

// SetDP040048E sets field value
func (o *Acs5ProfilesValuesDP0406) SetDP040048E(v Acs5ProfilesValuesDP0406DP040048E) {
	o.DP040048E = v
}

// GetDP040049E returns the DP040049E field value
func (o *Acs5ProfilesValuesDP0406) GetDP040049E() Acs5ProfilesValuesDP0406DP040049E {
	if o == nil {
		var ret Acs5ProfilesValuesDP0406DP040049E
		return ret
	}

	return o.DP040049E
}

// GetDP040049EOk returns a tuple with the DP040049E field value
// and a boolean to check if the value has been set.
func (o *Acs5ProfilesValuesDP0406) GetDP040049EOk() (*Acs5ProfilesValuesDP0406DP040049E, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.DP040049E, true
}

// SetDP040049E sets field value
func (o *Acs5ProfilesValuesDP0406) SetDP040049E(v Acs5ProfilesValuesDP0406DP040049E) {
	o.DP040049E = v
}

func (o Acs5ProfilesValuesDP0406) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["MDBGroupName"] = o.MDBGroupName
	}
	if true {
		toSerialize["MDBGroupCode"] = o.MDBGroupCode
	}
	if true {
		toSerialize["DP040045E"] = o.DP040045E
	}
	if true {
		toSerialize["DP040045PE"] = o.DP040045PE
	}
	if true {
		toSerialize["DP040046E"] = o.DP040046E
	}
	if true {
		toSerialize["DP040046PE"] = o.DP040046PE
	}
	if true {
		toSerialize["DP040047E"] = o.DP040047E
	}
	if true {
		toSerialize["DP040047PE"] = o.DP040047PE
	}
	if true {
		toSerialize["DP040048E"] = o.DP040048E
	}
	if true {
		toSerialize["DP040049E"] = o.DP040049E
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *Acs5ProfilesValuesDP0406) UnmarshalJSON(bytes []byte) (err error) {
	varAcs5ProfilesValuesDP0406 := _Acs5ProfilesValuesDP0406{}

	if err = json.Unmarshal(bytes, &varAcs5ProfilesValuesDP0406); err == nil {
		*o = Acs5ProfilesValuesDP0406(varAcs5ProfilesValuesDP0406)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "MDBGroupName")
		delete(additionalProperties, "MDBGroupCode")
		delete(additionalProperties, "DP040045E")
		delete(additionalProperties, "DP040045PE")
		delete(additionalProperties, "DP040046E")
		delete(additionalProperties, "DP040046PE")
		delete(additionalProperties, "DP040047E")
		delete(additionalProperties, "DP040047PE")
		delete(additionalProperties, "DP040048E")
		delete(additionalProperties, "DP040049E")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAcs5ProfilesValuesDP0406 struct {
	value *Acs5ProfilesValuesDP0406
	isSet bool
}

func (v NullableAcs5ProfilesValuesDP0406) Get() *Acs5ProfilesValuesDP0406 {
	return v.value
}

func (v *NullableAcs5ProfilesValuesDP0406) Set(val *Acs5ProfilesValuesDP0406) {
	v.value = val
	v.isSet = true
}

func (v NullableAcs5ProfilesValuesDP0406) IsSet() bool {
	return v.isSet
}

func (v *NullableAcs5ProfilesValuesDP0406) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAcs5ProfilesValuesDP0406(val *Acs5ProfilesValuesDP0406) *NullableAcs5ProfilesValuesDP0406 {
	return &NullableAcs5ProfilesValuesDP0406{value: val, isSet: true}
}

func (v NullableAcs5ProfilesValuesDP0406) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAcs5ProfilesValuesDP0406) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


