/*
 * Geo Spatial Query Api - US Census Boundaries and Census Data
 *
 * Easily integrate geospatial point-in-polygon search, census boundaries, location-based data, geofencing, and other location-based features into web and mobile apps. Our Software Development Kit (SDK) is available on GitHub at https://github.com/geospatialqueryapi/geospatialqueryapi-sdk. If possible then we are strongly recommending using our tested libraries available on GitHub, rather than creating new ones.      Copyright © 2021 Mobile Data Books, LLC. All Rights Reserved.  
 *
 * API version: 1.0.0
 * Contact: mobiledatabooks@mobiledatabooks.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// Acs5ProfilesValuesDP0407 YEAR HOUSEHOLDER MOVED INTO UNIT
type Acs5ProfilesValuesDP0407 struct {
	// YEAR HOUSEHOLDER MOVED INTO UNIT
	MDBGroupName string `json:"MDBGroupName"`
	// DP0407
	MDBGroupCode string `json:"MDBGroupCode"`
	DP040050E Acs5ProfilesValuesDP0407DP040050E `json:"DP040050E"`
	DP040051E Acs5ProfilesValuesDP0407DP040051E `json:"DP040051E"`
	DP040051PE Acs5ProfilesValuesDP0407DP040051PE `json:"DP040051PE"`
	DP040052E Acs5ProfilesValuesDP0407DP040052E `json:"DP040052E"`
	DP040052PE Acs5ProfilesValuesDP0407DP040052PE `json:"DP040052PE"`
	DP040053E Acs5ProfilesValuesDP0407DP040053E `json:"DP040053E"`
	DP040053PE Acs5ProfilesValuesDP0407DP040053PE `json:"DP040053PE"`
	DP040054E Acs5ProfilesValuesDP0407DP040054E `json:"DP040054E"`
	DP040054PE Acs5ProfilesValuesDP0407DP040054PE `json:"DP040054PE"`
	DP040055E Acs5ProfilesValuesDP0407DP040055E `json:"DP040055E"`
	DP040055PE Acs5ProfilesValuesDP0407DP040055PE `json:"DP040055PE"`
	DP040056E Acs5ProfilesValuesDP0407DP040056E `json:"DP040056E"`
	DP040056PE Acs5ProfilesValuesDP0407DP040056PE `json:"DP040056PE"`
	AdditionalProperties map[string]interface{}
}

type _Acs5ProfilesValuesDP0407 Acs5ProfilesValuesDP0407

// NewAcs5ProfilesValuesDP0407 instantiates a new Acs5ProfilesValuesDP0407 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAcs5ProfilesValuesDP0407(mDBGroupName string, mDBGroupCode string, dP040050E Acs5ProfilesValuesDP0407DP040050E, dP040051E Acs5ProfilesValuesDP0407DP040051E, dP040051PE Acs5ProfilesValuesDP0407DP040051PE, dP040052E Acs5ProfilesValuesDP0407DP040052E, dP040052PE Acs5ProfilesValuesDP0407DP040052PE, dP040053E Acs5ProfilesValuesDP0407DP040053E, dP040053PE Acs5ProfilesValuesDP0407DP040053PE, dP040054E Acs5ProfilesValuesDP0407DP040054E, dP040054PE Acs5ProfilesValuesDP0407DP040054PE, dP040055E Acs5ProfilesValuesDP0407DP040055E, dP040055PE Acs5ProfilesValuesDP0407DP040055PE, dP040056E Acs5ProfilesValuesDP0407DP040056E, dP040056PE Acs5ProfilesValuesDP0407DP040056PE) *Acs5ProfilesValuesDP0407 {
	this := Acs5ProfilesValuesDP0407{}
	this.MDBGroupName = mDBGroupName
	this.MDBGroupCode = mDBGroupCode
	this.DP040050E = dP040050E
	this.DP040051E = dP040051E
	this.DP040051PE = dP040051PE
	this.DP040052E = dP040052E
	this.DP040052PE = dP040052PE
	this.DP040053E = dP040053E
	this.DP040053PE = dP040053PE
	this.DP040054E = dP040054E
	this.DP040054PE = dP040054PE
	this.DP040055E = dP040055E
	this.DP040055PE = dP040055PE
	this.DP040056E = dP040056E
	this.DP040056PE = dP040056PE
	return &this
}

// NewAcs5ProfilesValuesDP0407WithDefaults instantiates a new Acs5ProfilesValuesDP0407 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAcs5ProfilesValuesDP0407WithDefaults() *Acs5ProfilesValuesDP0407 {
	this := Acs5ProfilesValuesDP0407{}
	return &this
}

// GetMDBGroupName returns the MDBGroupName field value
func (o *Acs5ProfilesValuesDP0407) GetMDBGroupName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MDBGroupName
}

// GetMDBGroupNameOk returns a tuple with the MDBGroupName field value
// and a boolean to check if the value has been set.
func (o *Acs5ProfilesValuesDP0407) GetMDBGroupNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.MDBGroupName, true
}

// SetMDBGroupName sets field value
func (o *Acs5ProfilesValuesDP0407) SetMDBGroupName(v string) {
	o.MDBGroupName = v
}

// GetMDBGroupCode returns the MDBGroupCode field value
func (o *Acs5ProfilesValuesDP0407) GetMDBGroupCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MDBGroupCode
}

// GetMDBGroupCodeOk returns a tuple with the MDBGroupCode field value
// and a boolean to check if the value has been set.
func (o *Acs5ProfilesValuesDP0407) GetMDBGroupCodeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.MDBGroupCode, true
}

// SetMDBGroupCode sets field value
func (o *Acs5ProfilesValuesDP0407) SetMDBGroupCode(v string) {
	o.MDBGroupCode = v
}

// GetDP040050E returns the DP040050E field value
func (o *Acs5ProfilesValuesDP0407) GetDP040050E() Acs5ProfilesValuesDP0407DP040050E {
	if o == nil {
		var ret Acs5ProfilesValuesDP0407DP040050E
		return ret
	}

	return o.DP040050E
}

// GetDP040050EOk returns a tuple with the DP040050E field value
// and a boolean to check if the value has been set.
func (o *Acs5ProfilesValuesDP0407) GetDP040050EOk() (*Acs5ProfilesValuesDP0407DP040050E, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.DP040050E, true
}

// SetDP040050E sets field value
func (o *Acs5ProfilesValuesDP0407) SetDP040050E(v Acs5ProfilesValuesDP0407DP040050E) {
	o.DP040050E = v
}

// GetDP040051E returns the DP040051E field value
func (o *Acs5ProfilesValuesDP0407) GetDP040051E() Acs5ProfilesValuesDP0407DP040051E {
	if o == nil {
		var ret Acs5ProfilesValuesDP0407DP040051E
		return ret
	}

	return o.DP040051E
}

// GetDP040051EOk returns a tuple with the DP040051E field value
// and a boolean to check if the value has been set.
func (o *Acs5ProfilesValuesDP0407) GetDP040051EOk() (*Acs5ProfilesValuesDP0407DP040051E, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.DP040051E, true
}

// SetDP040051E sets field value
func (o *Acs5ProfilesValuesDP0407) SetDP040051E(v Acs5ProfilesValuesDP0407DP040051E) {
	o.DP040051E = v
}

// GetDP040051PE returns the DP040051PE field value
func (o *Acs5ProfilesValuesDP0407) GetDP040051PE() Acs5ProfilesValuesDP0407DP040051PE {
	if o == nil {
		var ret Acs5ProfilesValuesDP0407DP040051PE
		return ret
	}

	return o.DP040051PE
}

// GetDP040051PEOk returns a tuple with the DP040051PE field value
// and a boolean to check if the value has been set.
func (o *Acs5ProfilesValuesDP0407) GetDP040051PEOk() (*Acs5ProfilesValuesDP0407DP040051PE, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.DP040051PE, true
}

// SetDP040051PE sets field value
func (o *Acs5ProfilesValuesDP0407) SetDP040051PE(v Acs5ProfilesValuesDP0407DP040051PE) {
	o.DP040051PE = v
}

// GetDP040052E returns the DP040052E field value
func (o *Acs5ProfilesValuesDP0407) GetDP040052E() Acs5ProfilesValuesDP0407DP040052E {
	if o == nil {
		var ret Acs5ProfilesValuesDP0407DP040052E
		return ret
	}

	return o.DP040052E
}

// GetDP040052EOk returns a tuple with the DP040052E field value
// and a boolean to check if the value has been set.
func (o *Acs5ProfilesValuesDP0407) GetDP040052EOk() (*Acs5ProfilesValuesDP0407DP040052E, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.DP040052E, true
}

// SetDP040052E sets field value
func (o *Acs5ProfilesValuesDP0407) SetDP040052E(v Acs5ProfilesValuesDP0407DP040052E) {
	o.DP040052E = v
}

// GetDP040052PE returns the DP040052PE field value
func (o *Acs5ProfilesValuesDP0407) GetDP040052PE() Acs5ProfilesValuesDP0407DP040052PE {
	if o == nil {
		var ret Acs5ProfilesValuesDP0407DP040052PE
		return ret
	}

	return o.DP040052PE
}

// GetDP040052PEOk returns a tuple with the DP040052PE field value
// and a boolean to check if the value has been set.
func (o *Acs5ProfilesValuesDP0407) GetDP040052PEOk() (*Acs5ProfilesValuesDP0407DP040052PE, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.DP040052PE, true
}

// SetDP040052PE sets field value
func (o *Acs5ProfilesValuesDP0407) SetDP040052PE(v Acs5ProfilesValuesDP0407DP040052PE) {
	o.DP040052PE = v
}

// GetDP040053E returns the DP040053E field value
func (o *Acs5ProfilesValuesDP0407) GetDP040053E() Acs5ProfilesValuesDP0407DP040053E {
	if o == nil {
		var ret Acs5ProfilesValuesDP0407DP040053E
		return ret
	}

	return o.DP040053E
}

// GetDP040053EOk returns a tuple with the DP040053E field value
// and a boolean to check if the value has been set.
func (o *Acs5ProfilesValuesDP0407) GetDP040053EOk() (*Acs5ProfilesValuesDP0407DP040053E, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.DP040053E, true
}

// SetDP040053E sets field value
func (o *Acs5ProfilesValuesDP0407) SetDP040053E(v Acs5ProfilesValuesDP0407DP040053E) {
	o.DP040053E = v
}

// GetDP040053PE returns the DP040053PE field value
func (o *Acs5ProfilesValuesDP0407) GetDP040053PE() Acs5ProfilesValuesDP0407DP040053PE {
	if o == nil {
		var ret Acs5ProfilesValuesDP0407DP040053PE
		return ret
	}

	return o.DP040053PE
}

// GetDP040053PEOk returns a tuple with the DP040053PE field value
// and a boolean to check if the value has been set.
func (o *Acs5ProfilesValuesDP0407) GetDP040053PEOk() (*Acs5ProfilesValuesDP0407DP040053PE, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.DP040053PE, true
}

// SetDP040053PE sets field value
func (o *Acs5ProfilesValuesDP0407) SetDP040053PE(v Acs5ProfilesValuesDP0407DP040053PE) {
	o.DP040053PE = v
}

// GetDP040054E returns the DP040054E field value
func (o *Acs5ProfilesValuesDP0407) GetDP040054E() Acs5ProfilesValuesDP0407DP040054E {
	if o == nil {
		var ret Acs5ProfilesValuesDP0407DP040054E
		return ret
	}

	return o.DP040054E
}

// GetDP040054EOk returns a tuple with the DP040054E field value
// and a boolean to check if the value has been set.
func (o *Acs5ProfilesValuesDP0407) GetDP040054EOk() (*Acs5ProfilesValuesDP0407DP040054E, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.DP040054E, true
}

// SetDP040054E sets field value
func (o *Acs5ProfilesValuesDP0407) SetDP040054E(v Acs5ProfilesValuesDP0407DP040054E) {
	o.DP040054E = v
}

// GetDP040054PE returns the DP040054PE field value
func (o *Acs5ProfilesValuesDP0407) GetDP040054PE() Acs5ProfilesValuesDP0407DP040054PE {
	if o == nil {
		var ret Acs5ProfilesValuesDP0407DP040054PE
		return ret
	}

	return o.DP040054PE
}

// GetDP040054PEOk returns a tuple with the DP040054PE field value
// and a boolean to check if the value has been set.
func (o *Acs5ProfilesValuesDP0407) GetDP040054PEOk() (*Acs5ProfilesValuesDP0407DP040054PE, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.DP040054PE, true
}

// SetDP040054PE sets field value
func (o *Acs5ProfilesValuesDP0407) SetDP040054PE(v Acs5ProfilesValuesDP0407DP040054PE) {
	o.DP040054PE = v
}

// GetDP040055E returns the DP040055E field value
func (o *Acs5ProfilesValuesDP0407) GetDP040055E() Acs5ProfilesValuesDP0407DP040055E {
	if o == nil {
		var ret Acs5ProfilesValuesDP0407DP040055E
		return ret
	}

	return o.DP040055E
}

// GetDP040055EOk returns a tuple with the DP040055E field value
// and a boolean to check if the value has been set.
func (o *Acs5ProfilesValuesDP0407) GetDP040055EOk() (*Acs5ProfilesValuesDP0407DP040055E, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.DP040055E, true
}

// SetDP040055E sets field value
func (o *Acs5ProfilesValuesDP0407) SetDP040055E(v Acs5ProfilesValuesDP0407DP040055E) {
	o.DP040055E = v
}

// GetDP040055PE returns the DP040055PE field value
func (o *Acs5ProfilesValuesDP0407) GetDP040055PE() Acs5ProfilesValuesDP0407DP040055PE {
	if o == nil {
		var ret Acs5ProfilesValuesDP0407DP040055PE
		return ret
	}

	return o.DP040055PE
}

// GetDP040055PEOk returns a tuple with the DP040055PE field value
// and a boolean to check if the value has been set.
func (o *Acs5ProfilesValuesDP0407) GetDP040055PEOk() (*Acs5ProfilesValuesDP0407DP040055PE, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.DP040055PE, true
}

// SetDP040055PE sets field value
func (o *Acs5ProfilesValuesDP0407) SetDP040055PE(v Acs5ProfilesValuesDP0407DP040055PE) {
	o.DP040055PE = v
}

// GetDP040056E returns the DP040056E field value
func (o *Acs5ProfilesValuesDP0407) GetDP040056E() Acs5ProfilesValuesDP0407DP040056E {
	if o == nil {
		var ret Acs5ProfilesValuesDP0407DP040056E
		return ret
	}

	return o.DP040056E
}

// GetDP040056EOk returns a tuple with the DP040056E field value
// and a boolean to check if the value has been set.
func (o *Acs5ProfilesValuesDP0407) GetDP040056EOk() (*Acs5ProfilesValuesDP0407DP040056E, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.DP040056E, true
}

// SetDP040056E sets field value
func (o *Acs5ProfilesValuesDP0407) SetDP040056E(v Acs5ProfilesValuesDP0407DP040056E) {
	o.DP040056E = v
}

// GetDP040056PE returns the DP040056PE field value
func (o *Acs5ProfilesValuesDP0407) GetDP040056PE() Acs5ProfilesValuesDP0407DP040056PE {
	if o == nil {
		var ret Acs5ProfilesValuesDP0407DP040056PE
		return ret
	}

	return o.DP040056PE
}

// GetDP040056PEOk returns a tuple with the DP040056PE field value
// and a boolean to check if the value has been set.
func (o *Acs5ProfilesValuesDP0407) GetDP040056PEOk() (*Acs5ProfilesValuesDP0407DP040056PE, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.DP040056PE, true
}

// SetDP040056PE sets field value
func (o *Acs5ProfilesValuesDP0407) SetDP040056PE(v Acs5ProfilesValuesDP0407DP040056PE) {
	o.DP040056PE = v
}

func (o Acs5ProfilesValuesDP0407) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["MDBGroupName"] = o.MDBGroupName
	}
	if true {
		toSerialize["MDBGroupCode"] = o.MDBGroupCode
	}
	if true {
		toSerialize["DP040050E"] = o.DP040050E
	}
	if true {
		toSerialize["DP040051E"] = o.DP040051E
	}
	if true {
		toSerialize["DP040051PE"] = o.DP040051PE
	}
	if true {
		toSerialize["DP040052E"] = o.DP040052E
	}
	if true {
		toSerialize["DP040052PE"] = o.DP040052PE
	}
	if true {
		toSerialize["DP040053E"] = o.DP040053E
	}
	if true {
		toSerialize["DP040053PE"] = o.DP040053PE
	}
	if true {
		toSerialize["DP040054E"] = o.DP040054E
	}
	if true {
		toSerialize["DP040054PE"] = o.DP040054PE
	}
	if true {
		toSerialize["DP040055E"] = o.DP040055E
	}
	if true {
		toSerialize["DP040055PE"] = o.DP040055PE
	}
	if true {
		toSerialize["DP040056E"] = o.DP040056E
	}
	if true {
		toSerialize["DP040056PE"] = o.DP040056PE
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *Acs5ProfilesValuesDP0407) UnmarshalJSON(bytes []byte) (err error) {
	varAcs5ProfilesValuesDP0407 := _Acs5ProfilesValuesDP0407{}

	if err = json.Unmarshal(bytes, &varAcs5ProfilesValuesDP0407); err == nil {
		*o = Acs5ProfilesValuesDP0407(varAcs5ProfilesValuesDP0407)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "MDBGroupName")
		delete(additionalProperties, "MDBGroupCode")
		delete(additionalProperties, "DP040050E")
		delete(additionalProperties, "DP040051E")
		delete(additionalProperties, "DP040051PE")
		delete(additionalProperties, "DP040052E")
		delete(additionalProperties, "DP040052PE")
		delete(additionalProperties, "DP040053E")
		delete(additionalProperties, "DP040053PE")
		delete(additionalProperties, "DP040054E")
		delete(additionalProperties, "DP040054PE")
		delete(additionalProperties, "DP040055E")
		delete(additionalProperties, "DP040055PE")
		delete(additionalProperties, "DP040056E")
		delete(additionalProperties, "DP040056PE")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAcs5ProfilesValuesDP0407 struct {
	value *Acs5ProfilesValuesDP0407
	isSet bool
}

func (v NullableAcs5ProfilesValuesDP0407) Get() *Acs5ProfilesValuesDP0407 {
	return v.value
}

func (v *NullableAcs5ProfilesValuesDP0407) Set(val *Acs5ProfilesValuesDP0407) {
	v.value = val
	v.isSet = true
}

func (v NullableAcs5ProfilesValuesDP0407) IsSet() bool {
	return v.isSet
}

func (v *NullableAcs5ProfilesValuesDP0407) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAcs5ProfilesValuesDP0407(val *Acs5ProfilesValuesDP0407) *NullableAcs5ProfilesValuesDP0407 {
	return &NullableAcs5ProfilesValuesDP0407{value: val, isSet: true}
}

func (v NullableAcs5ProfilesValuesDP0407) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAcs5ProfilesValuesDP0407) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


