/*
 * Geo Spatial Query Api - US Census Boundaries and Census Data
 *
 * Easily integrate geospatial point-in-polygon search, census boundaries, location-based data, geofencing, and other location-based features into web and mobile apps. Our Software Development Kit (SDK) is available on GitHub at https://github.com/geospatialqueryapi/geospatialqueryapi-sdk. If possible then we are strongly recommending using our tested libraries available on GitHub, rather than creating new ones. PDF documentation - ./pdf.html
 *
 * API version: 1.0.0
 * Contact: mobiledatabooks@mobiledatabooks.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// Acs5ProfilesValuesDP0402 struct for Acs5ProfilesValuesDP0402
type Acs5ProfilesValuesDP0402 struct {
	MDBGroupName string `json:"MDBGroupName"`
	MDBGroupCode string `json:"MDBGroupCode"`
	DP040006E Acs5ProfilesValuesDP0402DP040006E `json:"DP040006E"`
	DP040007E Acs5ProfilesValuesDP0402DP040007E `json:"DP040007E"`
	DP040007PE Acs5ProfilesValuesDP0402DP040007PE `json:"DP040007PE"`
	DP040008E Acs5ProfilesValuesDP0402DP040008E `json:"DP040008E"`
	DP040008PE Acs5ProfilesValuesDP0402DP040008PE `json:"DP040008PE"`
	DP040009E Acs5ProfilesValuesDP0402DP040009E `json:"DP040009E"`
	DP040009PE Acs5ProfilesValuesDP0402DP040009PE `json:"DP040009PE"`
	DP040010E Acs5ProfilesValuesDP0402DP040010E `json:"DP040010E"`
	DP040010PE Acs5ProfilesValuesDP0402DP040010PE `json:"DP040010PE"`
	DP040011E Acs5ProfilesValuesDP0402DP040011E `json:"DP040011E"`
	DP040011PE Acs5ProfilesValuesDP0402DP040011PE `json:"DP040011PE"`
	DP040012E Acs5ProfilesValuesDP0402DP040012E `json:"DP040012E"`
	DP040012PE Acs5ProfilesValuesDP0402DP040012PE `json:"DP040012PE"`
	DP040013E Acs5ProfilesValuesDP0402DP040013E `json:"DP040013E"`
	DP040013PE Acs5ProfilesValuesDP0402DP040013PE `json:"DP040013PE"`
	DP040014E Acs5ProfilesValuesDP0402DP040014E `json:"DP040014E"`
	DP040014PE Acs5ProfilesValuesDP0402DP040014PE `json:"DP040014PE"`
	DP040015E Acs5ProfilesValuesDP0402DP040015E `json:"DP040015E"`
	DP040015PE Acs5ProfilesValuesDP0402DP040015PE `json:"DP040015PE"`
	AdditionalProperties map[string]interface{}
}

type _Acs5ProfilesValuesDP0402 Acs5ProfilesValuesDP0402

// NewAcs5ProfilesValuesDP0402 instantiates a new Acs5ProfilesValuesDP0402 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAcs5ProfilesValuesDP0402(mDBGroupName string, mDBGroupCode string, dP040006E Acs5ProfilesValuesDP0402DP040006E, dP040007E Acs5ProfilesValuesDP0402DP040007E, dP040007PE Acs5ProfilesValuesDP0402DP040007PE, dP040008E Acs5ProfilesValuesDP0402DP040008E, dP040008PE Acs5ProfilesValuesDP0402DP040008PE, dP040009E Acs5ProfilesValuesDP0402DP040009E, dP040009PE Acs5ProfilesValuesDP0402DP040009PE, dP040010E Acs5ProfilesValuesDP0402DP040010E, dP040010PE Acs5ProfilesValuesDP0402DP040010PE, dP040011E Acs5ProfilesValuesDP0402DP040011E, dP040011PE Acs5ProfilesValuesDP0402DP040011PE, dP040012E Acs5ProfilesValuesDP0402DP040012E, dP040012PE Acs5ProfilesValuesDP0402DP040012PE, dP040013E Acs5ProfilesValuesDP0402DP040013E, dP040013PE Acs5ProfilesValuesDP0402DP040013PE, dP040014E Acs5ProfilesValuesDP0402DP040014E, dP040014PE Acs5ProfilesValuesDP0402DP040014PE, dP040015E Acs5ProfilesValuesDP0402DP040015E, dP040015PE Acs5ProfilesValuesDP0402DP040015PE) *Acs5ProfilesValuesDP0402 {
	this := Acs5ProfilesValuesDP0402{}
	this.MDBGroupName = mDBGroupName
	this.MDBGroupCode = mDBGroupCode
	this.DP040006E = dP040006E
	this.DP040007E = dP040007E
	this.DP040007PE = dP040007PE
	this.DP040008E = dP040008E
	this.DP040008PE = dP040008PE
	this.DP040009E = dP040009E
	this.DP040009PE = dP040009PE
	this.DP040010E = dP040010E
	this.DP040010PE = dP040010PE
	this.DP040011E = dP040011E
	this.DP040011PE = dP040011PE
	this.DP040012E = dP040012E
	this.DP040012PE = dP040012PE
	this.DP040013E = dP040013E
	this.DP040013PE = dP040013PE
	this.DP040014E = dP040014E
	this.DP040014PE = dP040014PE
	this.DP040015E = dP040015E
	this.DP040015PE = dP040015PE
	return &this
}

// NewAcs5ProfilesValuesDP0402WithDefaults instantiates a new Acs5ProfilesValuesDP0402 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAcs5ProfilesValuesDP0402WithDefaults() *Acs5ProfilesValuesDP0402 {
	this := Acs5ProfilesValuesDP0402{}
	return &this
}

// GetMDBGroupName returns the MDBGroupName field value
func (o *Acs5ProfilesValuesDP0402) GetMDBGroupName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MDBGroupName
}

// GetMDBGroupNameOk returns a tuple with the MDBGroupName field value
// and a boolean to check if the value has been set.
func (o *Acs5ProfilesValuesDP0402) GetMDBGroupNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.MDBGroupName, true
}

// SetMDBGroupName sets field value
func (o *Acs5ProfilesValuesDP0402) SetMDBGroupName(v string) {
	o.MDBGroupName = v
}

// GetMDBGroupCode returns the MDBGroupCode field value
func (o *Acs5ProfilesValuesDP0402) GetMDBGroupCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MDBGroupCode
}

// GetMDBGroupCodeOk returns a tuple with the MDBGroupCode field value
// and a boolean to check if the value has been set.
func (o *Acs5ProfilesValuesDP0402) GetMDBGroupCodeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.MDBGroupCode, true
}

// SetMDBGroupCode sets field value
func (o *Acs5ProfilesValuesDP0402) SetMDBGroupCode(v string) {
	o.MDBGroupCode = v
}

// GetDP040006E returns the DP040006E field value
func (o *Acs5ProfilesValuesDP0402) GetDP040006E() Acs5ProfilesValuesDP0402DP040006E {
	if o == nil {
		var ret Acs5ProfilesValuesDP0402DP040006E
		return ret
	}

	return o.DP040006E
}

// GetDP040006EOk returns a tuple with the DP040006E field value
// and a boolean to check if the value has been set.
func (o *Acs5ProfilesValuesDP0402) GetDP040006EOk() (*Acs5ProfilesValuesDP0402DP040006E, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.DP040006E, true
}

// SetDP040006E sets field value
func (o *Acs5ProfilesValuesDP0402) SetDP040006E(v Acs5ProfilesValuesDP0402DP040006E) {
	o.DP040006E = v
}

// GetDP040007E returns the DP040007E field value
func (o *Acs5ProfilesValuesDP0402) GetDP040007E() Acs5ProfilesValuesDP0402DP040007E {
	if o == nil {
		var ret Acs5ProfilesValuesDP0402DP040007E
		return ret
	}

	return o.DP040007E
}

// GetDP040007EOk returns a tuple with the DP040007E field value
// and a boolean to check if the value has been set.
func (o *Acs5ProfilesValuesDP0402) GetDP040007EOk() (*Acs5ProfilesValuesDP0402DP040007E, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.DP040007E, true
}

// SetDP040007E sets field value
func (o *Acs5ProfilesValuesDP0402) SetDP040007E(v Acs5ProfilesValuesDP0402DP040007E) {
	o.DP040007E = v
}

// GetDP040007PE returns the DP040007PE field value
func (o *Acs5ProfilesValuesDP0402) GetDP040007PE() Acs5ProfilesValuesDP0402DP040007PE {
	if o == nil {
		var ret Acs5ProfilesValuesDP0402DP040007PE
		return ret
	}

	return o.DP040007PE
}

// GetDP040007PEOk returns a tuple with the DP040007PE field value
// and a boolean to check if the value has been set.
func (o *Acs5ProfilesValuesDP0402) GetDP040007PEOk() (*Acs5ProfilesValuesDP0402DP040007PE, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.DP040007PE, true
}

// SetDP040007PE sets field value
func (o *Acs5ProfilesValuesDP0402) SetDP040007PE(v Acs5ProfilesValuesDP0402DP040007PE) {
	o.DP040007PE = v
}

// GetDP040008E returns the DP040008E field value
func (o *Acs5ProfilesValuesDP0402) GetDP040008E() Acs5ProfilesValuesDP0402DP040008E {
	if o == nil {
		var ret Acs5ProfilesValuesDP0402DP040008E
		return ret
	}

	return o.DP040008E
}

// GetDP040008EOk returns a tuple with the DP040008E field value
// and a boolean to check if the value has been set.
func (o *Acs5ProfilesValuesDP0402) GetDP040008EOk() (*Acs5ProfilesValuesDP0402DP040008E, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.DP040008E, true
}

// SetDP040008E sets field value
func (o *Acs5ProfilesValuesDP0402) SetDP040008E(v Acs5ProfilesValuesDP0402DP040008E) {
	o.DP040008E = v
}

// GetDP040008PE returns the DP040008PE field value
func (o *Acs5ProfilesValuesDP0402) GetDP040008PE() Acs5ProfilesValuesDP0402DP040008PE {
	if o == nil {
		var ret Acs5ProfilesValuesDP0402DP040008PE
		return ret
	}

	return o.DP040008PE
}

// GetDP040008PEOk returns a tuple with the DP040008PE field value
// and a boolean to check if the value has been set.
func (o *Acs5ProfilesValuesDP0402) GetDP040008PEOk() (*Acs5ProfilesValuesDP0402DP040008PE, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.DP040008PE, true
}

// SetDP040008PE sets field value
func (o *Acs5ProfilesValuesDP0402) SetDP040008PE(v Acs5ProfilesValuesDP0402DP040008PE) {
	o.DP040008PE = v
}

// GetDP040009E returns the DP040009E field value
func (o *Acs5ProfilesValuesDP0402) GetDP040009E() Acs5ProfilesValuesDP0402DP040009E {
	if o == nil {
		var ret Acs5ProfilesValuesDP0402DP040009E
		return ret
	}

	return o.DP040009E
}

// GetDP040009EOk returns a tuple with the DP040009E field value
// and a boolean to check if the value has been set.
func (o *Acs5ProfilesValuesDP0402) GetDP040009EOk() (*Acs5ProfilesValuesDP0402DP040009E, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.DP040009E, true
}

// SetDP040009E sets field value
func (o *Acs5ProfilesValuesDP0402) SetDP040009E(v Acs5ProfilesValuesDP0402DP040009E) {
	o.DP040009E = v
}

// GetDP040009PE returns the DP040009PE field value
func (o *Acs5ProfilesValuesDP0402) GetDP040009PE() Acs5ProfilesValuesDP0402DP040009PE {
	if o == nil {
		var ret Acs5ProfilesValuesDP0402DP040009PE
		return ret
	}

	return o.DP040009PE
}

// GetDP040009PEOk returns a tuple with the DP040009PE field value
// and a boolean to check if the value has been set.
func (o *Acs5ProfilesValuesDP0402) GetDP040009PEOk() (*Acs5ProfilesValuesDP0402DP040009PE, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.DP040009PE, true
}

// SetDP040009PE sets field value
func (o *Acs5ProfilesValuesDP0402) SetDP040009PE(v Acs5ProfilesValuesDP0402DP040009PE) {
	o.DP040009PE = v
}

// GetDP040010E returns the DP040010E field value
func (o *Acs5ProfilesValuesDP0402) GetDP040010E() Acs5ProfilesValuesDP0402DP040010E {
	if o == nil {
		var ret Acs5ProfilesValuesDP0402DP040010E
		return ret
	}

	return o.DP040010E
}

// GetDP040010EOk returns a tuple with the DP040010E field value
// and a boolean to check if the value has been set.
func (o *Acs5ProfilesValuesDP0402) GetDP040010EOk() (*Acs5ProfilesValuesDP0402DP040010E, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.DP040010E, true
}

// SetDP040010E sets field value
func (o *Acs5ProfilesValuesDP0402) SetDP040010E(v Acs5ProfilesValuesDP0402DP040010E) {
	o.DP040010E = v
}

// GetDP040010PE returns the DP040010PE field value
func (o *Acs5ProfilesValuesDP0402) GetDP040010PE() Acs5ProfilesValuesDP0402DP040010PE {
	if o == nil {
		var ret Acs5ProfilesValuesDP0402DP040010PE
		return ret
	}

	return o.DP040010PE
}

// GetDP040010PEOk returns a tuple with the DP040010PE field value
// and a boolean to check if the value has been set.
func (o *Acs5ProfilesValuesDP0402) GetDP040010PEOk() (*Acs5ProfilesValuesDP0402DP040010PE, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.DP040010PE, true
}

// SetDP040010PE sets field value
func (o *Acs5ProfilesValuesDP0402) SetDP040010PE(v Acs5ProfilesValuesDP0402DP040010PE) {
	o.DP040010PE = v
}

// GetDP040011E returns the DP040011E field value
func (o *Acs5ProfilesValuesDP0402) GetDP040011E() Acs5ProfilesValuesDP0402DP040011E {
	if o == nil {
		var ret Acs5ProfilesValuesDP0402DP040011E
		return ret
	}

	return o.DP040011E
}

// GetDP040011EOk returns a tuple with the DP040011E field value
// and a boolean to check if the value has been set.
func (o *Acs5ProfilesValuesDP0402) GetDP040011EOk() (*Acs5ProfilesValuesDP0402DP040011E, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.DP040011E, true
}

// SetDP040011E sets field value
func (o *Acs5ProfilesValuesDP0402) SetDP040011E(v Acs5ProfilesValuesDP0402DP040011E) {
	o.DP040011E = v
}

// GetDP040011PE returns the DP040011PE field value
func (o *Acs5ProfilesValuesDP0402) GetDP040011PE() Acs5ProfilesValuesDP0402DP040011PE {
	if o == nil {
		var ret Acs5ProfilesValuesDP0402DP040011PE
		return ret
	}

	return o.DP040011PE
}

// GetDP040011PEOk returns a tuple with the DP040011PE field value
// and a boolean to check if the value has been set.
func (o *Acs5ProfilesValuesDP0402) GetDP040011PEOk() (*Acs5ProfilesValuesDP0402DP040011PE, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.DP040011PE, true
}

// SetDP040011PE sets field value
func (o *Acs5ProfilesValuesDP0402) SetDP040011PE(v Acs5ProfilesValuesDP0402DP040011PE) {
	o.DP040011PE = v
}

// GetDP040012E returns the DP040012E field value
func (o *Acs5ProfilesValuesDP0402) GetDP040012E() Acs5ProfilesValuesDP0402DP040012E {
	if o == nil {
		var ret Acs5ProfilesValuesDP0402DP040012E
		return ret
	}

	return o.DP040012E
}

// GetDP040012EOk returns a tuple with the DP040012E field value
// and a boolean to check if the value has been set.
func (o *Acs5ProfilesValuesDP0402) GetDP040012EOk() (*Acs5ProfilesValuesDP0402DP040012E, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.DP040012E, true
}

// SetDP040012E sets field value
func (o *Acs5ProfilesValuesDP0402) SetDP040012E(v Acs5ProfilesValuesDP0402DP040012E) {
	o.DP040012E = v
}

// GetDP040012PE returns the DP040012PE field value
func (o *Acs5ProfilesValuesDP0402) GetDP040012PE() Acs5ProfilesValuesDP0402DP040012PE {
	if o == nil {
		var ret Acs5ProfilesValuesDP0402DP040012PE
		return ret
	}

	return o.DP040012PE
}

// GetDP040012PEOk returns a tuple with the DP040012PE field value
// and a boolean to check if the value has been set.
func (o *Acs5ProfilesValuesDP0402) GetDP040012PEOk() (*Acs5ProfilesValuesDP0402DP040012PE, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.DP040012PE, true
}

// SetDP040012PE sets field value
func (o *Acs5ProfilesValuesDP0402) SetDP040012PE(v Acs5ProfilesValuesDP0402DP040012PE) {
	o.DP040012PE = v
}

// GetDP040013E returns the DP040013E field value
func (o *Acs5ProfilesValuesDP0402) GetDP040013E() Acs5ProfilesValuesDP0402DP040013E {
	if o == nil {
		var ret Acs5ProfilesValuesDP0402DP040013E
		return ret
	}

	return o.DP040013E
}

// GetDP040013EOk returns a tuple with the DP040013E field value
// and a boolean to check if the value has been set.
func (o *Acs5ProfilesValuesDP0402) GetDP040013EOk() (*Acs5ProfilesValuesDP0402DP040013E, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.DP040013E, true
}

// SetDP040013E sets field value
func (o *Acs5ProfilesValuesDP0402) SetDP040013E(v Acs5ProfilesValuesDP0402DP040013E) {
	o.DP040013E = v
}

// GetDP040013PE returns the DP040013PE field value
func (o *Acs5ProfilesValuesDP0402) GetDP040013PE() Acs5ProfilesValuesDP0402DP040013PE {
	if o == nil {
		var ret Acs5ProfilesValuesDP0402DP040013PE
		return ret
	}

	return o.DP040013PE
}

// GetDP040013PEOk returns a tuple with the DP040013PE field value
// and a boolean to check if the value has been set.
func (o *Acs5ProfilesValuesDP0402) GetDP040013PEOk() (*Acs5ProfilesValuesDP0402DP040013PE, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.DP040013PE, true
}

// SetDP040013PE sets field value
func (o *Acs5ProfilesValuesDP0402) SetDP040013PE(v Acs5ProfilesValuesDP0402DP040013PE) {
	o.DP040013PE = v
}

// GetDP040014E returns the DP040014E field value
func (o *Acs5ProfilesValuesDP0402) GetDP040014E() Acs5ProfilesValuesDP0402DP040014E {
	if o == nil {
		var ret Acs5ProfilesValuesDP0402DP040014E
		return ret
	}

	return o.DP040014E
}

// GetDP040014EOk returns a tuple with the DP040014E field value
// and a boolean to check if the value has been set.
func (o *Acs5ProfilesValuesDP0402) GetDP040014EOk() (*Acs5ProfilesValuesDP0402DP040014E, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.DP040014E, true
}

// SetDP040014E sets field value
func (o *Acs5ProfilesValuesDP0402) SetDP040014E(v Acs5ProfilesValuesDP0402DP040014E) {
	o.DP040014E = v
}

// GetDP040014PE returns the DP040014PE field value
func (o *Acs5ProfilesValuesDP0402) GetDP040014PE() Acs5ProfilesValuesDP0402DP040014PE {
	if o == nil {
		var ret Acs5ProfilesValuesDP0402DP040014PE
		return ret
	}

	return o.DP040014PE
}

// GetDP040014PEOk returns a tuple with the DP040014PE field value
// and a boolean to check if the value has been set.
func (o *Acs5ProfilesValuesDP0402) GetDP040014PEOk() (*Acs5ProfilesValuesDP0402DP040014PE, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.DP040014PE, true
}

// SetDP040014PE sets field value
func (o *Acs5ProfilesValuesDP0402) SetDP040014PE(v Acs5ProfilesValuesDP0402DP040014PE) {
	o.DP040014PE = v
}

// GetDP040015E returns the DP040015E field value
func (o *Acs5ProfilesValuesDP0402) GetDP040015E() Acs5ProfilesValuesDP0402DP040015E {
	if o == nil {
		var ret Acs5ProfilesValuesDP0402DP040015E
		return ret
	}

	return o.DP040015E
}

// GetDP040015EOk returns a tuple with the DP040015E field value
// and a boolean to check if the value has been set.
func (o *Acs5ProfilesValuesDP0402) GetDP040015EOk() (*Acs5ProfilesValuesDP0402DP040015E, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.DP040015E, true
}

// SetDP040015E sets field value
func (o *Acs5ProfilesValuesDP0402) SetDP040015E(v Acs5ProfilesValuesDP0402DP040015E) {
	o.DP040015E = v
}

// GetDP040015PE returns the DP040015PE field value
func (o *Acs5ProfilesValuesDP0402) GetDP040015PE() Acs5ProfilesValuesDP0402DP040015PE {
	if o == nil {
		var ret Acs5ProfilesValuesDP0402DP040015PE
		return ret
	}

	return o.DP040015PE
}

// GetDP040015PEOk returns a tuple with the DP040015PE field value
// and a boolean to check if the value has been set.
func (o *Acs5ProfilesValuesDP0402) GetDP040015PEOk() (*Acs5ProfilesValuesDP0402DP040015PE, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.DP040015PE, true
}

// SetDP040015PE sets field value
func (o *Acs5ProfilesValuesDP0402) SetDP040015PE(v Acs5ProfilesValuesDP0402DP040015PE) {
	o.DP040015PE = v
}

func (o Acs5ProfilesValuesDP0402) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["MDBGroupName"] = o.MDBGroupName
	}
	if true {
		toSerialize["MDBGroupCode"] = o.MDBGroupCode
	}
	if true {
		toSerialize["DP040006E"] = o.DP040006E
	}
	if true {
		toSerialize["DP040007E"] = o.DP040007E
	}
	if true {
		toSerialize["DP040007PE"] = o.DP040007PE
	}
	if true {
		toSerialize["DP040008E"] = o.DP040008E
	}
	if true {
		toSerialize["DP040008PE"] = o.DP040008PE
	}
	if true {
		toSerialize["DP040009E"] = o.DP040009E
	}
	if true {
		toSerialize["DP040009PE"] = o.DP040009PE
	}
	if true {
		toSerialize["DP040010E"] = o.DP040010E
	}
	if true {
		toSerialize["DP040010PE"] = o.DP040010PE
	}
	if true {
		toSerialize["DP040011E"] = o.DP040011E
	}
	if true {
		toSerialize["DP040011PE"] = o.DP040011PE
	}
	if true {
		toSerialize["DP040012E"] = o.DP040012E
	}
	if true {
		toSerialize["DP040012PE"] = o.DP040012PE
	}
	if true {
		toSerialize["DP040013E"] = o.DP040013E
	}
	if true {
		toSerialize["DP040013PE"] = o.DP040013PE
	}
	if true {
		toSerialize["DP040014E"] = o.DP040014E
	}
	if true {
		toSerialize["DP040014PE"] = o.DP040014PE
	}
	if true {
		toSerialize["DP040015E"] = o.DP040015E
	}
	if true {
		toSerialize["DP040015PE"] = o.DP040015PE
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *Acs5ProfilesValuesDP0402) UnmarshalJSON(bytes []byte) (err error) {
	varAcs5ProfilesValuesDP0402 := _Acs5ProfilesValuesDP0402{}

	if err = json.Unmarshal(bytes, &varAcs5ProfilesValuesDP0402); err == nil {
		*o = Acs5ProfilesValuesDP0402(varAcs5ProfilesValuesDP0402)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "MDBGroupName")
		delete(additionalProperties, "MDBGroupCode")
		delete(additionalProperties, "DP040006E")
		delete(additionalProperties, "DP040007E")
		delete(additionalProperties, "DP040007PE")
		delete(additionalProperties, "DP040008E")
		delete(additionalProperties, "DP040008PE")
		delete(additionalProperties, "DP040009E")
		delete(additionalProperties, "DP040009PE")
		delete(additionalProperties, "DP040010E")
		delete(additionalProperties, "DP040010PE")
		delete(additionalProperties, "DP040011E")
		delete(additionalProperties, "DP040011PE")
		delete(additionalProperties, "DP040012E")
		delete(additionalProperties, "DP040012PE")
		delete(additionalProperties, "DP040013E")
		delete(additionalProperties, "DP040013PE")
		delete(additionalProperties, "DP040014E")
		delete(additionalProperties, "DP040014PE")
		delete(additionalProperties, "DP040015E")
		delete(additionalProperties, "DP040015PE")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAcs5ProfilesValuesDP0402 struct {
	value *Acs5ProfilesValuesDP0402
	isSet bool
}

func (v NullableAcs5ProfilesValuesDP0402) Get() *Acs5ProfilesValuesDP0402 {
	return v.value
}

func (v *NullableAcs5ProfilesValuesDP0402) Set(val *Acs5ProfilesValuesDP0402) {
	v.value = val
	v.isSet = true
}

func (v NullableAcs5ProfilesValuesDP0402) IsSet() bool {
	return v.isSet
}

func (v *NullableAcs5ProfilesValuesDP0402) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAcs5ProfilesValuesDP0402(val *Acs5ProfilesValuesDP0402) *NullableAcs5ProfilesValuesDP0402 {
	return &NullableAcs5ProfilesValuesDP0402{value: val, isSet: true}
}

func (v NullableAcs5ProfilesValuesDP0402) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAcs5ProfilesValuesDP0402) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


